//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosConsumidorFinal
    {
        public int confi_Id { get; set; }
        public long fact_Id { get; set; }
        public string confi_Nombres { get; set; }
        public string confi_Telefono { get; set; }
        public string confi_Correo { get; set; }
    
        public virtual tbFactura tbFactura { get; set; }
        public virtual tbFactura tbFactura1 { get; set; }
        public virtual tbFactura tbFactura2 { get; set; }
        public virtual tbFactura tbFactura3 { get; set; }
        public virtual tbFactura tbFactura4 { get; set; }
        public virtual tbFactura tbFactura5 { get; set; }
        public virtual tbFactura tbFactura6 { get; set; }
        public virtual tbFactura tbFactura7 { get; set; }
        public virtual tbFactura tbFactura8 { get; set; }
        public virtual tbFactura tbFactura9 { get; set; }
        public virtual tbFactura tbFactura10 { get; set; }
        public virtual tbFactura tbFactura11 { get; set; }
        public virtual tbFactura tbFactura12 { get; set; }
        public virtual tbFactura tbFactura13 { get; set; }
        public virtual tbFactura tbFactura14 { get; set; }
        public virtual tbFactura tbFactura15 { get; set; }
        public virtual tbFactura tbFactura16 { get; set; }
        public virtual tbFactura tbFactura17 { get; set; }
        public virtual tbFactura tbFactura18 { get; set; }
        public virtual tbFactura tbFactura19 { get; set; }
        public virtual tbFactura tbFactura20 { get; set; }
        public virtual tbFactura tbFactura21 { get; set; }
        public virtual tbFactura tbFactura22 { get; set; }
        public virtual tbFactura tbFactura23 { get; set; }
        public virtual tbFactura tbFactura24 { get; set; }
        public virtual tbFactura tbFactura25 { get; set; }
        public virtual tbFactura tbFactura26 { get; set; }
        public virtual tbFactura tbFactura27 { get; set; }
        public virtual tbFactura tbFactura28 { get; set; }
        public virtual tbFactura tbFactura29 { get; set; }
        public virtual tbFactura tbFactura30 { get; set; }
        public virtual tbFactura tbFactura31 { get; set; }
        public virtual tbFactura tbFactura32 { get; set; }
        public virtual tbFactura tbFactura33 { get; set; }
        public virtual tbFactura tbFactura34 { get; set; }
        public virtual tbFactura tbFactura35 { get; set; }
        public virtual tbFactura tbFactura36 { get; set; }
        public virtual tbFactura tbFactura37 { get; set; }
        public virtual tbFactura tbFactura38 { get; set; }
        public virtual tbFactura tbFactura39 { get; set; }
        public virtual tbFactura tbFactura40 { get; set; }
        public virtual tbFactura tbFactura41 { get; set; }
    }
}
