//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ERP_GMEDINAEntities : DbContext
    {
        public ERP_GMEDINAEntities()
            : base("name=ERP_GMEDINAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbUsuario> tbUsuario { get; set; }
        public virtual DbSet<tbEmpleados> tbEmpleados { get; set; }
        public virtual DbSet<tbHistorialSalidas> tbHistorialSalidas { get; set; }
        public virtual DbSet<tbPersonas> tbPersonas { get; set; }
        public virtual DbSet<tbRazonSalidas> tbRazonSalidas { get; set; }
        public virtual DbSet<tbTipoSalidas> tbTipoSalidas { get; set; }
        public virtual DbSet<V_tbHistorialSalidas_completa> V_tbHistorialSalidas_completa { get; set; }
        public virtual DbSet<V_HistorialSalidas_Empleados> V_HistorialSalidas_Empleados { get; set; }
        public virtual DbSet<tbTipoHoras> tbTipoHoras { get; set; }
    
        public virtual ObjectResult<UDP_RRHH_tbTipoSalidas_Delete_Result> UDP_RRHH_tbTipoSalidas_Delete(Nullable<int> tsal_id, string tsal_razon_Inactivo, Nullable<int> tsal_UsuarioModifica, Nullable<System.DateTime> tsal_FechaModifica)
        {
            var tsal_idParameter = tsal_id.HasValue ?
                new ObjectParameter("tsal_id", tsal_id) :
                new ObjectParameter("tsal_id", typeof(int));
    
            var tsal_razon_InactivoParameter = tsal_razon_Inactivo != null ?
                new ObjectParameter("tsal_razon_Inactivo", tsal_razon_Inactivo) :
                new ObjectParameter("tsal_razon_Inactivo", typeof(string));
    
            var tsal_UsuarioModificaParameter = tsal_UsuarioModifica.HasValue ?
                new ObjectParameter("tsal_UsuarioModifica", tsal_UsuarioModifica) :
                new ObjectParameter("tsal_UsuarioModifica", typeof(int));
    
            var tsal_FechaModificaParameter = tsal_FechaModifica.HasValue ?
                new ObjectParameter("tsal_FechaModifica", tsal_FechaModifica) :
                new ObjectParameter("tsal_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_RRHH_tbTipoSalidas_Delete_Result>("UDP_RRHH_tbTipoSalidas_Delete", tsal_idParameter, tsal_razon_InactivoParameter, tsal_UsuarioModificaParameter, tsal_FechaModificaParameter);
        }
    
        public virtual ObjectResult<UDP_RRHH_tbTipoSalidas_Insert_Result> UDP_RRHH_tbTipoSalidas_Insert(string tsal_Descripcion, Nullable<int> tsal_UsuarioCrea, Nullable<System.DateTime> tsal_FechaCrea)
        {
            var tsal_DescripcionParameter = tsal_Descripcion != null ?
                new ObjectParameter("tsal_Descripcion", tsal_Descripcion) :
                new ObjectParameter("tsal_Descripcion", typeof(string));
    
            var tsal_UsuarioCreaParameter = tsal_UsuarioCrea.HasValue ?
                new ObjectParameter("tsal_UsuarioCrea", tsal_UsuarioCrea) :
                new ObjectParameter("tsal_UsuarioCrea", typeof(int));
    
            var tsal_FechaCreaParameter = tsal_FechaCrea.HasValue ?
                new ObjectParameter("tsal_FechaCrea", tsal_FechaCrea) :
                new ObjectParameter("tsal_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_RRHH_tbTipoSalidas_Insert_Result>("UDP_RRHH_tbTipoSalidas_Insert", tsal_DescripcionParameter, tsal_UsuarioCreaParameter, tsal_FechaCreaParameter);
        }
    
        public virtual ObjectResult<UDP_RRHH_tbTipoSalidas_Update_Result> UDP_RRHH_tbTipoSalidas_Update(Nullable<int> tsal_Id, string tsal_Descripcion, Nullable<int> tsal_UsuarioModifica, Nullable<System.DateTime> tsal_FechaModifica)
        {
            var tsal_IdParameter = tsal_Id.HasValue ?
                new ObjectParameter("tsal_Id", tsal_Id) :
                new ObjectParameter("tsal_Id", typeof(int));
    
            var tsal_DescripcionParameter = tsal_Descripcion != null ?
                new ObjectParameter("tsal_Descripcion", tsal_Descripcion) :
                new ObjectParameter("tsal_Descripcion", typeof(string));
    
            var tsal_UsuarioModificaParameter = tsal_UsuarioModifica.HasValue ?
                new ObjectParameter("tsal_UsuarioModifica", tsal_UsuarioModifica) :
                new ObjectParameter("tsal_UsuarioModifica", typeof(int));
    
            var tsal_FechaModificaParameter = tsal_FechaModifica.HasValue ?
                new ObjectParameter("tsal_FechaModifica", tsal_FechaModifica) :
                new ObjectParameter("tsal_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_RRHH_tbTipoSalidas_Update_Result>("UDP_RRHH_tbTipoSalidas_Update", tsal_IdParameter, tsal_DescripcionParameter, tsal_UsuarioModificaParameter, tsal_FechaModificaParameter);
        }
    
        public virtual ObjectResult<UDP_RRHH_tbHistorialSalidas_Delete_Result> UDP_RRHH_tbHistorialSalidas_Delete(Nullable<int> hsal_Id, string hsal_RazonInactivo, Nullable<int> hsal_UsuarioModifica, Nullable<System.DateTime> hsal_FechaModifica)
        {
            var hsal_IdParameter = hsal_Id.HasValue ?
                new ObjectParameter("Hsal_Id", hsal_Id) :
                new ObjectParameter("Hsal_Id", typeof(int));
    
            var hsal_RazonInactivoParameter = hsal_RazonInactivo != null ?
                new ObjectParameter("hsal_RazonInactivo", hsal_RazonInactivo) :
                new ObjectParameter("hsal_RazonInactivo", typeof(string));
    
            var hsal_UsuarioModificaParameter = hsal_UsuarioModifica.HasValue ?
                new ObjectParameter("hsal_UsuarioModifica", hsal_UsuarioModifica) :
                new ObjectParameter("hsal_UsuarioModifica", typeof(int));
    
            var hsal_FechaModificaParameter = hsal_FechaModifica.HasValue ?
                new ObjectParameter("hsal_FechaModifica", hsal_FechaModifica) :
                new ObjectParameter("hsal_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_RRHH_tbHistorialSalidas_Delete_Result>("UDP_RRHH_tbHistorialSalidas_Delete", hsal_IdParameter, hsal_RazonInactivoParameter, hsal_UsuarioModificaParameter, hsal_FechaModificaParameter);
        }
    
        public virtual ObjectResult<UDP_RRHH_tbHistorialSalidas_Restore_Result> UDP_RRHH_tbHistorialSalidas_Restore(Nullable<int> hsal_Id, Nullable<int> hsal_UsuarioModifica, Nullable<System.DateTime> hsal_FechaModifica)
        {
            var hsal_IdParameter = hsal_Id.HasValue ?
                new ObjectParameter("Hsal_Id", hsal_Id) :
                new ObjectParameter("Hsal_Id", typeof(int));
    
            var hsal_UsuarioModificaParameter = hsal_UsuarioModifica.HasValue ?
                new ObjectParameter("hsal_UsuarioModifica", hsal_UsuarioModifica) :
                new ObjectParameter("hsal_UsuarioModifica", typeof(int));
    
            var hsal_FechaModificaParameter = hsal_FechaModifica.HasValue ?
                new ObjectParameter("hsal_FechaModifica", hsal_FechaModifica) :
                new ObjectParameter("hsal_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_RRHH_tbHistorialSalidas_Restore_Result>("UDP_RRHH_tbHistorialSalidas_Restore", hsal_IdParameter, hsal_UsuarioModificaParameter, hsal_FechaModificaParameter);
        }
    
        public virtual ObjectResult<UDP_RRHH_tbHistorialSalidas_Insert_Result> UDP_RRHH_tbHistorialSalidas_Insert(Nullable<int> emp_Id, Nullable<int> tsal_Id, Nullable<int> rsal_Id, Nullable<System.DateTime> hsal_FechaSalida, string hsal_Observacion, string emp_RazonInactivo, Nullable<int> hsal_UsuarioCrea, Nullable<System.DateTime> hsal_FechaCrea)
        {
            var emp_IdParameter = emp_Id.HasValue ?
                new ObjectParameter("emp_Id", emp_Id) :
                new ObjectParameter("emp_Id", typeof(int));
    
            var tsal_IdParameter = tsal_Id.HasValue ?
                new ObjectParameter("tsal_Id", tsal_Id) :
                new ObjectParameter("tsal_Id", typeof(int));
    
            var rsal_IdParameter = rsal_Id.HasValue ?
                new ObjectParameter("rsal_Id", rsal_Id) :
                new ObjectParameter("rsal_Id", typeof(int));
    
            var hsal_FechaSalidaParameter = hsal_FechaSalida.HasValue ?
                new ObjectParameter("hsal_FechaSalida", hsal_FechaSalida) :
                new ObjectParameter("hsal_FechaSalida", typeof(System.DateTime));
    
            var hsal_ObservacionParameter = hsal_Observacion != null ?
                new ObjectParameter("hsal_Observacion", hsal_Observacion) :
                new ObjectParameter("hsal_Observacion", typeof(string));
    
            var emp_RazonInactivoParameter = emp_RazonInactivo != null ?
                new ObjectParameter("emp_RazonInactivo", emp_RazonInactivo) :
                new ObjectParameter("emp_RazonInactivo", typeof(string));
    
            var hsal_UsuarioCreaParameter = hsal_UsuarioCrea.HasValue ?
                new ObjectParameter("hsal_UsuarioCrea", hsal_UsuarioCrea) :
                new ObjectParameter("hsal_UsuarioCrea", typeof(int));
    
            var hsal_FechaCreaParameter = hsal_FechaCrea.HasValue ?
                new ObjectParameter("hsal_FechaCrea", hsal_FechaCrea) :
                new ObjectParameter("hsal_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_RRHH_tbHistorialSalidas_Insert_Result>("UDP_RRHH_tbHistorialSalidas_Insert", emp_IdParameter, tsal_IdParameter, rsal_IdParameter, hsal_FechaSalidaParameter, hsal_ObservacionParameter, emp_RazonInactivoParameter, hsal_UsuarioCreaParameter, hsal_FechaCreaParameter);
        }
    
        public virtual ObjectResult<UDP_RRHH_tbHistorialSalidas_Update_Result> UDP_RRHH_tbHistorialSalidas_Update(Nullable<int> hsal_Id, string hsal_Observacion, Nullable<int> hsal_UsuarioModifica, Nullable<System.DateTime> fare_FechaModifica)
        {
            var hsal_IdParameter = hsal_Id.HasValue ?
                new ObjectParameter("hsal_Id", hsal_Id) :
                new ObjectParameter("hsal_Id", typeof(int));
    
            var hsal_ObservacionParameter = hsal_Observacion != null ?
                new ObjectParameter("hsal_Observacion", hsal_Observacion) :
                new ObjectParameter("hsal_Observacion", typeof(string));
    
            var hsal_UsuarioModificaParameter = hsal_UsuarioModifica.HasValue ?
                new ObjectParameter("hsal_UsuarioModifica", hsal_UsuarioModifica) :
                new ObjectParameter("hsal_UsuarioModifica", typeof(int));
    
            var fare_FechaModificaParameter = fare_FechaModifica.HasValue ?
                new ObjectParameter("fare_FechaModifica", fare_FechaModifica) :
                new ObjectParameter("fare_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_RRHH_tbHistorialSalidas_Update_Result>("UDP_RRHH_tbHistorialSalidas_Update", hsal_IdParameter, hsal_ObservacionParameter, hsal_UsuarioModificaParameter, fare_FechaModificaParameter);
        }
    }
}
