//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAuxilioDeCesantias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbAuxilioDeCesantias()
        {
            this.tbLiquidaciones = new HashSet<tbLiquidaciones>();
        }
    
        public int aces_IdAuxilioCesantia { get; set; }
        public int aces_RangoInicioMeses { get; set; }
        public int aces_RangoFinMeses { get; set; }
        public int aces_DiasAuxilioCesantia { get; set; }
        public int aces_UsuarioCrea { get; set; }
        public System.DateTime aces_FechaCrea { get; set; }
        public Nullable<int> aces_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> aces_FechaModifica { get; set; }
        public bool aces_Activo { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLiquidaciones> tbLiquidaciones { get; set; }
    }
}
