//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFaseSeleccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbFaseSeleccion()
        {
            this.tbSeleccionCandidatos = new HashSet<tbSeleccionCandidatos>();
        }
    
        public int fsel_Id { get; set; }
        public int fare_Id { get; set; }
        public System.DateTime fsel_Fecha { get; set; }
        public bool fsel_Estado { get; set; }
        public string fsel_RazonInactivo { get; set; }
        public int fsel_UsuarioCrea { get; set; }
        public System.DateTime fsel_FechaCrea { get; set; }
        public Nullable<int> fsel_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> fsel_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSeleccionCandidatos> tbSeleccionCandidatos { get; set; }
        public virtual tbFasesReclutamiento tbFasesReclutamiento { get; set; }
    }
}
