//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHistorialRefrendamientos
    {
        public int href_Id { get; set; }
        public int emp_Id { get; set; }
        public string href_Archivo { get; set; }
        public System.DateTime href_FechaRefrendado { get; set; }
        public bool href_Estado { get; set; }
        public string href_RazonInactivo { get; set; }
        public int href_UsuarioCrea { get; set; }
        public System.DateTime href_FechaCrea { get; set; }
        public Nullable<int> href_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> href_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        public virtual tbEmpleados tbEmpleados { get; set; }
    }
}
