//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbIdiomas
    {
        public int idi_Id { get; set; }
        public string idi_Descripcion { get; set; }
        public bool idi_Estado { get; set; }
        public string idi_RazonInactivo { get; set; }
        public int idi_UsuarioCrea { get; set; }
        public System.DateTime idi_FechaCrea { get; set; }
        public Nullable<int> idi_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> idi_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
    }
}
