//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLiquidacionVacaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbLiquidacionVacaciones()
        {
            this.tbLiquidaciones = new HashSet<tbLiquidaciones>();
        }
    
        public int pvac_IdPagoVacaciones { get; set; }
        public int pvac_Antiguedad { get; set; }
        public int pvac_dias { get; set; }
        public int pvac_UsuarioCrea { get; set; }
        public System.DateTime pvac_FechaCrea { get; set; }
        public Nullable<int> pvac_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> pvac_FechaModifica { get; set; }
        public bool pvac_Activo { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLiquidaciones> tbLiquidaciones { get; set; }
    }
}
