//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTipoIncapacidades
    {
        public int ticn_Id { get; set; }
        public string ticn_Descripcion { get; set; }
        public bool ticn_Estado { get; set; }
        public string ticn_RazonInactivo { get; set; }
        public int ticn_UsuarioCrea { get; set; }
        public System.DateTime ticn_FechaCrea { get; set; }
        public Nullable<int> ticn_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> ticn_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
    }
}
