//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTipoMonedas
    {
        public int tmon_Id { get; set; }
        public string tmon_Descripcion { get; set; }
        public bool tmon_Estado { get; set; }
        public string tmon_RazonInactivo { get; set; }
        public int tmon_UsuarioCrea { get; set; }
        public System.DateTime tmon_FechaCrea { get; set; }
        public Nullable<int> tmon_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> tmon_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
    }
}
