//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTipoPermisos
    {
        public int tper_Id { get; set; }
        public string tper_Descripcion { get; set; }
        public bool tper_Estado { get; set; }
        public string tper_RazonInactivo { get; set; }
        public int tper_UsuarioCrea { get; set; }
        public System.DateTime tper_FechaCrea { get; set; }
        public Nullable<int> tper_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> tper_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
    }
}
