//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbVacaciones
    {
        public int vaca_Id { get; set; }
        public int emp_Id { get; set; }
        public Nullable<int> vaca_Dias { get; set; }
        public bool vaca_Estado { get; set; }
        public string vaca_RazonInactivo { get; set; }
        public int vaca_UsuarioCrea { get; set; }
        public System.DateTime vaca_FechaCrea { get; set; }
        public Nullable<int> vaca_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> vaca_FechaModifica { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual tbUsuario tbUsuario1 { get; set; }
        public virtual tbEmpleados tbEmpleados { get; set; }
    }
}
