//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DatosRequisicion
    {
        public string Descripcion { get; set; }
        public string TipoDato { get; set; }
        public int Data_Id { get; set; }
        public int req_Id { get; set; }
    }
}
