//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Datos_Empleado
    {
        public int emp_Id { get; set; }
        public int area_Id { get; set; }
        public string area_Descripcion { get; set; }
        public int car_Id { get; set; }
        public string car_Descripcion { get; set; }
        public int depto_Id { get; set; }
        public string depto_Descripcion { get; set; }
        public string jor_Descripcion { get; set; }
    }
}
