//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DeduccionesExtraordinarias_EquipoEmpleado
    {
        public int eqem_Id { get; set; }
        public int eqtra_Id { get; set; }
        public string eqtra_Codigo { get; set; }
        public string per_EquipoEmpleado { get; set; }
    }
}
