//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FaseSeleccion
    {
        public int per_Id { get; set; }
        public int scan_Id { get; set; }
        public int fsel_Id { get; set; }
        public string Fase { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
