//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Plani_HistorialIngreso
    {
        public int emp_Id { get; set; }
        public int hipa_IdHistorialDePago { get; set; }
        public string cin_DescripcionIngreso { get; set; }
        public Nullable<decimal> hip_TotalPagar { get; set; }
        public System.DateTime hipa_FechaPago { get; set; }
        public string nombreEmpleado { get; set; }
        public string identidadEmpleado { get; set; }
        public int cpla_IdPlanilla { get; set; }
    }
}
