//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RPT_HistorialVacaciones
    {
        public int hvac_Id { get; set; }
        public int emp_Id { get; set; }
        public string Nombre_Empleado { get; set; }
        public int hvac_CantDias { get; set; }
        public System.DateTime hvac_FechaInicio { get; set; }
        public bool hvac_DiasPagados { get; set; }
        public int hvac_MesVacaciones { get; set; }
        public int hvac_anioVacaciones { get; set; }
        public System.DateTime hvac_FechaFin { get; set; }
    }
}
