//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RPT_Requisiciones
    {
        public int Id_Requisicion { get; set; }
        public int Id_Persona { get; set; }
        public string Identidad { get; set; }
        public string Nombre_Completo { get; set; }
        public string Descripcion { get; set; }
        public string Duracion { get; set; }
        public int Edad_Minima { get; set; }
        public int Edad_Maxima { get; set; }
        public string Educacion_Superior { get; set; }
        public string Experiencia { get; set; }
        public Nullable<System.DateTime> Fecha_Requisicion { get; set; }
        public Nullable<System.DateTime> Fecha_Contratacion { get; set; }
        public string Sexo { get; set; }
        public string Permanente { get; set; }
        public string Titulos { get; set; }
        public string Competencias { get; set; }
        public string Habilidades { get; set; }
        public string Idiomas { get; set; }
        public string Requerimientos_Especiales { get; set; }
    }
}
