//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RPT_HistorialAudienciaDescargo
    {
        public int aude_Id { get; set; }
        public string nombre { get; set; }
        public string per_Identidad { get; set; }
        public string aude_Descripcion { get; set; }
        public System.DateTime fechaAudiencia { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
