//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RPT_HistorialPermisos
    {
        public int hper_Id { get; set; }
        public int emp_Id { get; set; }
        public string Identidad { get; set; }
        public string NombreCompleto { get; set; }
        public int tper_Id { get; set; }
        public string TipoPermiso { get; set; }
        public bool emp_Estado { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
    }
}
