//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RPT_HistorialAudienciaDescargo
    {
        public int aude_Id { get; set; }
        public string nombre { get; set; }
        public string per_Identidad { get; set; }
        public string aude_Descripcion { get; set; }
        public System.DateTime aude_fechaaudiencia { get; set; }
    }
}
