//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SeleccionCandidatos
    {
        public int Id { get; set; }
        public string Identidad { get; set; }
        public string Nombre { get; set; }
        public string Fase { get; set; }
        public string Plaza_Solicitada { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public System.DateTime Fecha_Crea { get; set; }
        public int Usuario_Crea { get; set; }
        public Nullable<System.DateTime> Fecha_Modifica { get; set; }
        public Nullable<int> Usuario_Modifica { get; set; }
        public string Razon_Inactivo { get; set; }
    }
}
