//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ERP_GMEDINAEntities : DbContext
    {
        public ERP_GMEDINAEntities()
            : base("name=ERP_GMEDINAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAccesoRol> tbAccesoRol { get; set; }
        public virtual DbSet<tbObjeto> tbObjeto { get; set; }
        public virtual DbSet<tbRol> tbRol { get; set; }
        public virtual DbSet<tbRolesUsuario> tbRolesUsuario { get; set; }
        public virtual DbSet<tbUsuario> tbUsuario { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbAdelantoSueldo> tbAdelantoSueldo { get; set; }
        public virtual DbSet<tbAuxilioDeCesantias> tbAuxilioDeCesantias { get; set; }
        public virtual DbSet<tbCatalogoDeDeducciones> tbCatalogoDeDeducciones { get; set; }
        public virtual DbSet<tbCatalogoDeIngresos> tbCatalogoDeIngresos { get; set; }
        public virtual DbSet<tbCatalogoDePlanillas> tbCatalogoDePlanillas { get; set; }
        public virtual DbSet<tbDecimoCuartoMes> tbDecimoCuartoMes { get; set; }
        public virtual DbSet<tbDecimoTercerMes> tbDecimoTercerMes { get; set; }
        public virtual DbSet<tbDeduccionesExtraordinarias> tbDeduccionesExtraordinarias { get; set; }
        public virtual DbSet<tbDeduccionInstitucionFinanciera> tbDeduccionInstitucionFinanciera { get; set; }
        public virtual DbSet<tbEmpleadoBonos> tbEmpleadoBonos { get; set; }
        public virtual DbSet<tbEmpleadoComisiones> tbEmpleadoComisiones { get; set; }
        public virtual DbSet<tbFormaPago> tbFormaPago { get; set; }
        public virtual DbSet<tbHistorialDeduccionPago> tbHistorialDeduccionPago { get; set; }
        public virtual DbSet<tbHistorialDeIngresosPago> tbHistorialDeIngresosPago { get; set; }
        public virtual DbSet<tbHistorialDePago> tbHistorialDePago { get; set; }
        public virtual DbSet<tbInstitucionesFinancieras> tbInstitucionesFinancieras { get; set; }
        public virtual DbSet<tbISR> tbISR { get; set; }
        public virtual DbSet<tbLiquidaciones> tbLiquidaciones { get; set; }
        public virtual DbSet<tbLiquidacionVacaciones> tbLiquidacionVacaciones { get; set; }
        public virtual DbSet<tbMotivoLiquidaciones> tbMotivoLiquidaciones { get; set; }
        public virtual DbSet<tbPeriodos> tbPeriodos { get; set; }
        public virtual DbSet<tbPreaviso> tbPreaviso { get; set; }
        public virtual DbSet<tbRamaActividad> tbRamaActividad { get; set; }
        public virtual DbSet<tbSalarioPorHora> tbSalarioPorHora { get; set; }
        public virtual DbSet<tbTechosDeducciones> tbTechosDeducciones { get; set; }
        public virtual DbSet<tbTipoDeduccion> tbTipoDeduccion { get; set; }
        public virtual DbSet<tbTipoPlanillaDetalleDeduccion> tbTipoPlanillaDetalleDeduccion { get; set; }
        public virtual DbSet<tbTipoPlanillaDetalleIngreso> tbTipoPlanillaDetalleIngreso { get; set; }
        public virtual DbSet<tbAreas> tbAreas { get; set; }
        public virtual DbSet<tbCargos> tbCargos { get; set; }
        public virtual DbSet<tbCompetencias> tbCompetencias { get; set; }
        public virtual DbSet<tbCompetenciasPersona> tbCompetenciasPersona { get; set; }
        public virtual DbSet<tbCompetenciasRequisicion> tbCompetenciasRequisicion { get; set; }
        public virtual DbSet<tbDepartamentos> tbDepartamentos { get; set; }
        public virtual DbSet<tbEmpleados> tbEmpleados { get; set; }
        public virtual DbSet<tbEmpresas> tbEmpresas { get; set; }
        public virtual DbSet<tbEquipoEmpleados> tbEquipoEmpleados { get; set; }
        public virtual DbSet<tbEquipoTrabajo> tbEquipoTrabajo { get; set; }
        public virtual DbSet<tbFaseSeleccion> tbFaseSeleccion { get; set; }
        public virtual DbSet<tbFasesReclutamiento> tbFasesReclutamiento { get; set; }
        public virtual DbSet<tbHabilidades> tbHabilidades { get; set; }
        public virtual DbSet<tbHabilidadesPersona> tbHabilidadesPersona { get; set; }
        public virtual DbSet<tbHabilidadesRequisicion> tbHabilidadesRequisicion { get; set; }
        public virtual DbSet<tbHistorialAmonestaciones> tbHistorialAmonestaciones { get; set; }
        public virtual DbSet<tbHistorialAudienciaDescargo> tbHistorialAudienciaDescargo { get; set; }
        public virtual DbSet<tbHistorialCargos> tbHistorialCargos { get; set; }
        public virtual DbSet<tbHistorialContrataciones> tbHistorialContrataciones { get; set; }
        public virtual DbSet<tbHistorialHorasTrabajadas> tbHistorialHorasTrabajadas { get; set; }
        public virtual DbSet<tbHistorialIncapacidades> tbHistorialIncapacidades { get; set; }
        public virtual DbSet<tbHistorialLiquidaciones> tbHistorialLiquidaciones { get; set; }
        public virtual DbSet<tbHistorialPermisos> tbHistorialPermisos { get; set; }
        public virtual DbSet<tbHistorialRefrendamientos> tbHistorialRefrendamientos { get; set; }
        public virtual DbSet<tbHistorialSalidas> tbHistorialSalidas { get; set; }
        public virtual DbSet<tbHistorialVacaciones> tbHistorialVacaciones { get; set; }
        public virtual DbSet<tbHorarios> tbHorarios { get; set; }
        public virtual DbSet<tbIdiomaPersona> tbIdiomaPersona { get; set; }
        public virtual DbSet<tbIdiomas> tbIdiomas { get; set; }
        public virtual DbSet<tbIdiomasRequisicion> tbIdiomasRequisicion { get; set; }
        public virtual DbSet<tbJornadas> tbJornadas { get; set; }
        public virtual DbSet<tbNacionalidades> tbNacionalidades { get; set; }
        public virtual DbSet<tbPersonas> tbPersonas { get; set; }
        public virtual DbSet<tbRazonSalidas> tbRazonSalidas { get; set; }
        public virtual DbSet<tbRequisiciones> tbRequisiciones { get; set; }
        public virtual DbSet<tbSeleccionCandidatos> tbSeleccionCandidatos { get; set; }
        public virtual DbSet<tbSucursales> tbSucursales { get; set; }
        public virtual DbSet<tbSueldos> tbSueldos { get; set; }
        public virtual DbSet<tbTipoAmonestaciones> tbTipoAmonestaciones { get; set; }
        public virtual DbSet<tbTipoHoras> tbTipoHoras { get; set; }
        public virtual DbSet<tbTipoIncapacidades> tbTipoIncapacidades { get; set; }
        public virtual DbSet<tbTipoMonedas> tbTipoMonedas { get; set; }
        public virtual DbSet<tbTipoPermisos> tbTipoPermisos { get; set; }
        public virtual DbSet<tbTipoSalidas> tbTipoSalidas { get; set; }
        public virtual DbSet<tbTitulos> tbTitulos { get; set; }
        public virtual DbSet<tbTitulosPersona> tbTitulosPersona { get; set; }
        public virtual DbSet<tbTitulosRequisicion> tbTitulosRequisicion { get; set; }
        public virtual DbSet<tbVacaciones> tbVacaciones { get; set; }
        public virtual DbSet<V_Plani_EmpleadoPorPlanilla> V_Plani_EmpleadoPorPlanilla { get; set; }
        public virtual DbSet<V_Plani_FechaPlanilla> V_Plani_FechaPlanilla { get; set; }
        public virtual DbSet<V_Plani_TipoPlani> V_Plani_TipoPlani { get; set; }
        public virtual DbSet<V_BonosColaborador> V_BonosColaborador { get; set; }
        public virtual DbSet<V_CatalogoDeIngresos> V_CatalogoDeIngresos { get; set; }
        public virtual DbSet<V_CatalogoDePlanillasConIngresosYDeducciones> V_CatalogoDePlanillasConIngresosYDeducciones { get; set; }
        public virtual DbSet<V_ColaboradoresPorPlanilla> V_ColaboradoresPorPlanilla { get; set; }
        public virtual DbSet<V_ComisionesColaborador> V_ComisionesColaborador { get; set; }
        public virtual DbSet<V_DecimoCuartoMes> V_DecimoCuartoMes { get; set; }
        public virtual DbSet<V_DecimoTercerMes> V_DecimoTercerMes { get; set; }
        public virtual DbSet<V_DecimoTercerMes_RPT> V_DecimoTercerMes_RPT { get; set; }
        public virtual DbSet<V_DeduccionesExtraordinarias_Detalles> V_DeduccionesExtraordinarias_Detalles { get; set; }
        public virtual DbSet<V_DeduccionesExtraordinarias_EquipoEmpleado> V_DeduccionesExtraordinarias_EquipoEmpleado { get; set; }
        public virtual DbSet<V_DeduccionesExtrasColaboradores> V_DeduccionesExtrasColaboradores { get; set; }
        public virtual DbSet<V_DeduccionesInstitucionesFinancierasColaboradres> V_DeduccionesInstitucionesFinancierasColaboradres { get; set; }
        public virtual DbSet<V_EmpleadoBonos> V_EmpleadoBonos { get; set; }
        public virtual DbSet<V_FormaDePago> V_FormaDePago { get; set; }
        public virtual DbSet<V_InformacionColaborador> V_InformacionColaborador { get; set; }
        public virtual DbSet<V_Plani_ReporteIHSS> V_Plani_ReporteIHSS { get; set; }
        public virtual DbSet<V_PlanillaDeducciones> V_PlanillaDeducciones { get; set; }
        public virtual DbSet<V_PlanillaIngresos> V_PlanillaIngresos { get; set; }
        public virtual DbSet<V_PreviewPlanilla> V_PreviewPlanilla { get; set; }
        public virtual DbSet<V_tbCatalogoDeDeducciones> V_tbCatalogoDeDeducciones { get; set; }
        public virtual DbSet<V_tbCatalogoDeIngresos> V_tbCatalogoDeIngresos { get; set; }
        public virtual DbSet<V_tbEmpleadoComisiones> V_tbEmpleadoComisiones { get; set; }
        public virtual DbSet<V_TechosDeducciones> V_TechosDeducciones { get; set; }
        public virtual DbSet<V_TipoDeduccion> V_TipoDeduccion { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<UDP_Plani_CatalogoDeduccionesEdit_Select_Result> UDP_Plani_CatalogoDeduccionesEdit_Select(Nullable<int> cpla_IdPlanilla)
        {
            var cpla_IdPlanillaParameter = cpla_IdPlanilla.HasValue ?
                new ObjectParameter("cpla_IdPlanilla", cpla_IdPlanilla) :
                new ObjectParameter("cpla_IdPlanilla", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Plani_CatalogoDeduccionesEdit_Select_Result>("UDP_Plani_CatalogoDeduccionesEdit_Select", cpla_IdPlanillaParameter);
        }
    
        public virtual ObjectResult<UDP_Plani_CatalogoDeIngresosEdit_Select_Result> UDP_Plani_CatalogoDeIngresosEdit_Select(Nullable<int> cpla_IdPlanilla)
        {
            var cpla_IdPlanillaParameter = cpla_IdPlanilla.HasValue ?
                new ObjectParameter("cpla_IdPlanilla", cpla_IdPlanilla) :
                new ObjectParameter("cpla_IdPlanilla", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Plani_CatalogoDeIngresosEdit_Select_Result>("UDP_Plani_CatalogoDeIngresosEdit_Select", cpla_IdPlanillaParameter);
        }
    
        public virtual ObjectResult<UDP_Plani_DecimoTercerMes_RPT_Result> UDP_Plani_DecimoTercerMes_RPT(Nullable<System.DateTime> fechaInicio)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UDP_Plani_DecimoTercerMes_RPT_Result>("UDP_Plani_DecimoTercerMes_RPT", fechaInicioParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_EmpleadoComisiones_Activar(Nullable<int> cc_Id, Nullable<int> cc_UsuarioModifica, Nullable<System.DateTime> cc_FechaModifcia)
        {
            var cc_IdParameter = cc_Id.HasValue ?
                new ObjectParameter("cc_Id", cc_Id) :
                new ObjectParameter("cc_Id", typeof(int));
    
            var cc_UsuarioModificaParameter = cc_UsuarioModifica.HasValue ?
                new ObjectParameter("cc_UsuarioModifica", cc_UsuarioModifica) :
                new ObjectParameter("cc_UsuarioModifica", typeof(int));
    
            var cc_FechaModifciaParameter = cc_FechaModifcia.HasValue ?
                new ObjectParameter("cc_FechaModifcia", cc_FechaModifcia) :
                new ObjectParameter("cc_FechaModifcia", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_EmpleadoComisiones_Activar", cc_IdParameter, cc_UsuarioModificaParameter, cc_FechaModifciaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_EmpleadoComisiones_Inactivar(Nullable<int> cc_Id, Nullable<int> cc_UsuarioModifica, Nullable<System.DateTime> cc_FechaModifcia)
        {
            var cc_IdParameter = cc_Id.HasValue ?
                new ObjectParameter("cc_Id", cc_Id) :
                new ObjectParameter("cc_Id", typeof(int));
    
            var cc_UsuarioModificaParameter = cc_UsuarioModifica.HasValue ?
                new ObjectParameter("cc_UsuarioModifica", cc_UsuarioModifica) :
                new ObjectParameter("cc_UsuarioModifica", typeof(int));
    
            var cc_FechaModifciaParameter = cc_FechaModifcia.HasValue ?
                new ObjectParameter("cc_FechaModifcia", cc_FechaModifcia) :
                new ObjectParameter("cc_FechaModifcia", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_EmpleadoComisiones_Inactivar", cc_IdParameter, cc_UsuarioModificaParameter, cc_FechaModifciaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_EmpleadoComisiones_Insert(Nullable<int> emp_Id, Nullable<int> cin_IdIngreso, Nullable<System.DateTime> cc_FechaRegistro, Nullable<bool> cc_Pagado, Nullable<int> cc_UsuarioCrea, Nullable<System.DateTime> cc_FechaCrea, Nullable<decimal> cc_PorcentajeComision, Nullable<decimal> cc_TotalVenta)
        {
            var emp_IdParameter = emp_Id.HasValue ?
                new ObjectParameter("emp_Id", emp_Id) :
                new ObjectParameter("emp_Id", typeof(int));
    
            var cin_IdIngresoParameter = cin_IdIngreso.HasValue ?
                new ObjectParameter("cin_IdIngreso", cin_IdIngreso) :
                new ObjectParameter("cin_IdIngreso", typeof(int));
    
            var cc_FechaRegistroParameter = cc_FechaRegistro.HasValue ?
                new ObjectParameter("cc_FechaRegistro", cc_FechaRegistro) :
                new ObjectParameter("cc_FechaRegistro", typeof(System.DateTime));
    
            var cc_PagadoParameter = cc_Pagado.HasValue ?
                new ObjectParameter("cc_Pagado", cc_Pagado) :
                new ObjectParameter("cc_Pagado", typeof(bool));
    
            var cc_UsuarioCreaParameter = cc_UsuarioCrea.HasValue ?
                new ObjectParameter("cc_UsuarioCrea", cc_UsuarioCrea) :
                new ObjectParameter("cc_UsuarioCrea", typeof(int));
    
            var cc_FechaCreaParameter = cc_FechaCrea.HasValue ?
                new ObjectParameter("cc_FechaCrea", cc_FechaCrea) :
                new ObjectParameter("cc_FechaCrea", typeof(System.DateTime));
    
            var cc_PorcentajeComisionParameter = cc_PorcentajeComision.HasValue ?
                new ObjectParameter("cc_PorcentajeComision", cc_PorcentajeComision) :
                new ObjectParameter("cc_PorcentajeComision", typeof(decimal));
    
            var cc_TotalVentaParameter = cc_TotalVenta.HasValue ?
                new ObjectParameter("cc_TotalVenta", cc_TotalVenta) :
                new ObjectParameter("cc_TotalVenta", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_EmpleadoComisiones_Insert", emp_IdParameter, cin_IdIngresoParameter, cc_FechaRegistroParameter, cc_PagadoParameter, cc_UsuarioCreaParameter, cc_FechaCreaParameter, cc_PorcentajeComisionParameter, cc_TotalVentaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_EmpleadoComisiones_Update(Nullable<int> cc_Id, Nullable<int> eMP_Id, Nullable<int> cc_UsuarioModifica, Nullable<System.DateTime> cc_FechaModifica, Nullable<decimal> cc_PorcentajeComision, Nullable<decimal> cc_TotalVenta)
        {
            var cc_IdParameter = cc_Id.HasValue ?
                new ObjectParameter("cc_Id", cc_Id) :
                new ObjectParameter("cc_Id", typeof(int));
    
            var eMP_IdParameter = eMP_Id.HasValue ?
                new ObjectParameter("EMP_Id", eMP_Id) :
                new ObjectParameter("EMP_Id", typeof(int));
    
            var cc_UsuarioModificaParameter = cc_UsuarioModifica.HasValue ?
                new ObjectParameter("cc_UsuarioModifica", cc_UsuarioModifica) :
                new ObjectParameter("cc_UsuarioModifica", typeof(int));
    
            var cc_FechaModificaParameter = cc_FechaModifica.HasValue ?
                new ObjectParameter("cc_FechaModifica", cc_FechaModifica) :
                new ObjectParameter("cc_FechaModifica", typeof(System.DateTime));
    
            var cc_PorcentajeComisionParameter = cc_PorcentajeComision.HasValue ?
                new ObjectParameter("cc_PorcentajeComision", cc_PorcentajeComision) :
                new ObjectParameter("cc_PorcentajeComision", typeof(decimal));
    
            var cc_TotalVentaParameter = cc_TotalVenta.HasValue ?
                new ObjectParameter("cc_TotalVenta", cc_TotalVenta) :
                new ObjectParameter("cc_TotalVenta", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_EmpleadoComisiones_Update", cc_IdParameter, eMP_IdParameter, cc_UsuarioModificaParameter, cc_FechaModificaParameter, cc_PorcentajeComisionParameter, cc_TotalVentaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbAdelantoSueldo_Activar(Nullable<int> adsu_IdAdelantoSueldo, Nullable<int> adsu_UsuarioModifica, Nullable<System.DateTime> adsu_FechaModifica)
        {
            var adsu_IdAdelantoSueldoParameter = adsu_IdAdelantoSueldo.HasValue ?
                new ObjectParameter("adsu_IdAdelantoSueldo", adsu_IdAdelantoSueldo) :
                new ObjectParameter("adsu_IdAdelantoSueldo", typeof(int));
    
            var adsu_UsuarioModificaParameter = adsu_UsuarioModifica.HasValue ?
                new ObjectParameter("adsu_UsuarioModifica", adsu_UsuarioModifica) :
                new ObjectParameter("adsu_UsuarioModifica", typeof(int));
    
            var adsu_FechaModificaParameter = adsu_FechaModifica.HasValue ?
                new ObjectParameter("adsu_FechaModifica", adsu_FechaModifica) :
                new ObjectParameter("adsu_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbAdelantoSueldo_Activar", adsu_IdAdelantoSueldoParameter, adsu_UsuarioModificaParameter, adsu_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbAdelantoSueldo_Inactivar(Nullable<int> adsu_IdAdelantoSueldo, Nullable<int> adsu_UsuarioModifica, Nullable<System.DateTime> adsu_FechaModifica)
        {
            var adsu_IdAdelantoSueldoParameter = adsu_IdAdelantoSueldo.HasValue ?
                new ObjectParameter("adsu_IdAdelantoSueldo", adsu_IdAdelantoSueldo) :
                new ObjectParameter("adsu_IdAdelantoSueldo", typeof(int));
    
            var adsu_UsuarioModificaParameter = adsu_UsuarioModifica.HasValue ?
                new ObjectParameter("adsu_UsuarioModifica", adsu_UsuarioModifica) :
                new ObjectParameter("adsu_UsuarioModifica", typeof(int));
    
            var adsu_FechaModificaParameter = adsu_FechaModifica.HasValue ?
                new ObjectParameter("adsu_FechaModifica", adsu_FechaModifica) :
                new ObjectParameter("adsu_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbAdelantoSueldo_Inactivar", adsu_IdAdelantoSueldoParameter, adsu_UsuarioModificaParameter, adsu_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbAdelantoSueldo_Insert(Nullable<int> emp_Id, Nullable<System.DateTime> adsu_FechaAdelanto, string adsu_RazonAdelanto, Nullable<decimal> adsu_Monto, Nullable<int> peri_IdPeriodo, Nullable<int> cde_IdDeducciones, Nullable<bool> adsu_Pagado, Nullable<int> adsu_UsuarioCrea, Nullable<System.DateTime> adsu_FechaCrea)
        {
            var emp_IdParameter = emp_Id.HasValue ?
                new ObjectParameter("emp_Id", emp_Id) :
                new ObjectParameter("emp_Id", typeof(int));
    
            var adsu_FechaAdelantoParameter = adsu_FechaAdelanto.HasValue ?
                new ObjectParameter("adsu_FechaAdelanto", adsu_FechaAdelanto) :
                new ObjectParameter("adsu_FechaAdelanto", typeof(System.DateTime));
    
            var adsu_RazonAdelantoParameter = adsu_RazonAdelanto != null ?
                new ObjectParameter("adsu_RazonAdelanto", adsu_RazonAdelanto) :
                new ObjectParameter("adsu_RazonAdelanto", typeof(string));
    
            var adsu_MontoParameter = adsu_Monto.HasValue ?
                new ObjectParameter("adsu_Monto", adsu_Monto) :
                new ObjectParameter("adsu_Monto", typeof(decimal));
    
            var peri_IdPeriodoParameter = peri_IdPeriodo.HasValue ?
                new ObjectParameter("peri_IdPeriodo", peri_IdPeriodo) :
                new ObjectParameter("peri_IdPeriodo", typeof(int));
    
            var cde_IdDeduccionesParameter = cde_IdDeducciones.HasValue ?
                new ObjectParameter("cde_IdDeducciones", cde_IdDeducciones) :
                new ObjectParameter("cde_IdDeducciones", typeof(int));
    
            var adsu_PagadoParameter = adsu_Pagado.HasValue ?
                new ObjectParameter("adsu_Pagado", adsu_Pagado) :
                new ObjectParameter("adsu_Pagado", typeof(bool));
    
            var adsu_UsuarioCreaParameter = adsu_UsuarioCrea.HasValue ?
                new ObjectParameter("adsu_UsuarioCrea", adsu_UsuarioCrea) :
                new ObjectParameter("adsu_UsuarioCrea", typeof(int));
    
            var adsu_FechaCreaParameter = adsu_FechaCrea.HasValue ?
                new ObjectParameter("adsu_FechaCrea", adsu_FechaCrea) :
                new ObjectParameter("adsu_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbAdelantoSueldo_Insert", emp_IdParameter, adsu_FechaAdelantoParameter, adsu_RazonAdelantoParameter, adsu_MontoParameter, peri_IdPeriodoParameter, cde_IdDeduccionesParameter, adsu_PagadoParameter, adsu_UsuarioCreaParameter, adsu_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbAdelantoSueldo_Update(Nullable<int> adsu_IdAdelantoSueldo, Nullable<int> emp_Id, string adsu_RazonAdelanto, Nullable<decimal> adsu_Monto, Nullable<int> peri_IdPeriodo, Nullable<bool> adsu_Pagado, Nullable<int> adsu_UsuarioModifica, Nullable<System.DateTime> adsu_FechaModifica)
        {
            var adsu_IdAdelantoSueldoParameter = adsu_IdAdelantoSueldo.HasValue ?
                new ObjectParameter("adsu_IdAdelantoSueldo", adsu_IdAdelantoSueldo) :
                new ObjectParameter("adsu_IdAdelantoSueldo", typeof(int));
    
            var emp_IdParameter = emp_Id.HasValue ?
                new ObjectParameter("emp_Id", emp_Id) :
                new ObjectParameter("emp_Id", typeof(int));
    
            var adsu_RazonAdelantoParameter = adsu_RazonAdelanto != null ?
                new ObjectParameter("adsu_RazonAdelanto", adsu_RazonAdelanto) :
                new ObjectParameter("adsu_RazonAdelanto", typeof(string));
    
            var adsu_MontoParameter = adsu_Monto.HasValue ?
                new ObjectParameter("adsu_Monto", adsu_Monto) :
                new ObjectParameter("adsu_Monto", typeof(decimal));
    
            var peri_IdPeriodoParameter = peri_IdPeriodo.HasValue ?
                new ObjectParameter("peri_IdPeriodo", peri_IdPeriodo) :
                new ObjectParameter("peri_IdPeriodo", typeof(int));
    
            var adsu_PagadoParameter = adsu_Pagado.HasValue ?
                new ObjectParameter("adsu_Pagado", adsu_Pagado) :
                new ObjectParameter("adsu_Pagado", typeof(bool));
    
            var adsu_UsuarioModificaParameter = adsu_UsuarioModifica.HasValue ?
                new ObjectParameter("adsu_UsuarioModifica", adsu_UsuarioModifica) :
                new ObjectParameter("adsu_UsuarioModifica", typeof(int));
    
            var adsu_FechaModificaParameter = adsu_FechaModifica.HasValue ?
                new ObjectParameter("adsu_FechaModifica", adsu_FechaModifica) :
                new ObjectParameter("adsu_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbAdelantoSueldo_Update", adsu_IdAdelantoSueldoParameter, emp_IdParameter, adsu_RazonAdelantoParameter, adsu_MontoParameter, peri_IdPeriodoParameter, adsu_PagadoParameter, adsu_UsuarioModificaParameter, adsu_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbCatalogoDeDeducciones_Activar(Nullable<int> cde_IdDeduccion, Nullable<int> cde_UsuarioModifica, Nullable<System.DateTime> cde_FechaModifica)
        {
            var cde_IdDeduccionParameter = cde_IdDeduccion.HasValue ?
                new ObjectParameter("cde_IdDeduccion", cde_IdDeduccion) :
                new ObjectParameter("cde_IdDeduccion", typeof(int));
    
            var cde_UsuarioModificaParameter = cde_UsuarioModifica.HasValue ?
                new ObjectParameter("cde_UsuarioModifica", cde_UsuarioModifica) :
                new ObjectParameter("cde_UsuarioModifica", typeof(int));
    
            var cde_FechaModificaParameter = cde_FechaModifica.HasValue ?
                new ObjectParameter("cde_FechaModifica", cde_FechaModifica) :
                new ObjectParameter("cde_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbCatalogoDeDeducciones_Activar", cde_IdDeduccionParameter, cde_UsuarioModificaParameter, cde_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbCatalogoDeDeducciones_Inactivar(Nullable<int> cde_IdDeduccion, Nullable<int> cde_UsuarioModifica, Nullable<System.DateTime> cde_FechaModifica)
        {
            var cde_IdDeduccionParameter = cde_IdDeduccion.HasValue ?
                new ObjectParameter("cde_IdDeduccion", cde_IdDeduccion) :
                new ObjectParameter("cde_IdDeduccion", typeof(int));
    
            var cde_UsuarioModificaParameter = cde_UsuarioModifica.HasValue ?
                new ObjectParameter("cde_UsuarioModifica", cde_UsuarioModifica) :
                new ObjectParameter("cde_UsuarioModifica", typeof(int));
    
            var cde_FechaModificaParameter = cde_FechaModifica.HasValue ?
                new ObjectParameter("cde_FechaModifica", cde_FechaModifica) :
                new ObjectParameter("cde_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbCatalogoDeDeducciones_Inactivar", cde_IdDeduccionParameter, cde_UsuarioModificaParameter, cde_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbCatalogoDeDeducciones_Insert(string cde_DescripcionDedu, Nullable<int> tde_IdTipoDedu, Nullable<decimal> cde_PorcentajeColaborador, Nullable<decimal> cde_PorcentajeEmpresa, Nullable<int> cde_UsuarioCrea, Nullable<System.DateTime> cde_FechaCrea)
        {
            var cde_DescripcionDeduParameter = cde_DescripcionDedu != null ?
                new ObjectParameter("cde_DescripcionDedu", cde_DescripcionDedu) :
                new ObjectParameter("cde_DescripcionDedu", typeof(string));
    
            var tde_IdTipoDeduParameter = tde_IdTipoDedu.HasValue ?
                new ObjectParameter("tde_IdTipoDedu", tde_IdTipoDedu) :
                new ObjectParameter("tde_IdTipoDedu", typeof(int));
    
            var cde_PorcentajeColaboradorParameter = cde_PorcentajeColaborador.HasValue ?
                new ObjectParameter("cde_PorcentajeColaborador", cde_PorcentajeColaborador) :
                new ObjectParameter("cde_PorcentajeColaborador", typeof(decimal));
    
            var cde_PorcentajeEmpresaParameter = cde_PorcentajeEmpresa.HasValue ?
                new ObjectParameter("cde_PorcentajeEmpresa", cde_PorcentajeEmpresa) :
                new ObjectParameter("cde_PorcentajeEmpresa", typeof(decimal));
    
            var cde_UsuarioCreaParameter = cde_UsuarioCrea.HasValue ?
                new ObjectParameter("cde_UsuarioCrea", cde_UsuarioCrea) :
                new ObjectParameter("cde_UsuarioCrea", typeof(int));
    
            var cde_FechaCreaParameter = cde_FechaCrea.HasValue ?
                new ObjectParameter("cde_FechaCrea", cde_FechaCrea) :
                new ObjectParameter("cde_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbCatalogoDeDeducciones_Insert", cde_DescripcionDeduParameter, tde_IdTipoDeduParameter, cde_PorcentajeColaboradorParameter, cde_PorcentajeEmpresaParameter, cde_UsuarioCreaParameter, cde_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbCatalogoDeDeducciones_Update(Nullable<int> cde_IdDeduccion, string cde_DescripcionDedu, Nullable<int> tde_IdTipoDedu, Nullable<decimal> cde_PorcentajeColaborador, Nullable<decimal> cde_PorcentajeEmpresa, Nullable<int> cde_UsuarioModifica, Nullable<System.DateTime> cde_FechaModifica)
        {
            var cde_IdDeduccionParameter = cde_IdDeduccion.HasValue ?
                new ObjectParameter("cde_IdDeduccion", cde_IdDeduccion) :
                new ObjectParameter("cde_IdDeduccion", typeof(int));
    
            var cde_DescripcionDeduParameter = cde_DescripcionDedu != null ?
                new ObjectParameter("cde_DescripcionDedu", cde_DescripcionDedu) :
                new ObjectParameter("cde_DescripcionDedu", typeof(string));
    
            var tde_IdTipoDeduParameter = tde_IdTipoDedu.HasValue ?
                new ObjectParameter("tde_IdTipoDedu", tde_IdTipoDedu) :
                new ObjectParameter("tde_IdTipoDedu", typeof(int));
    
            var cde_PorcentajeColaboradorParameter = cde_PorcentajeColaborador.HasValue ?
                new ObjectParameter("cde_PorcentajeColaborador", cde_PorcentajeColaborador) :
                new ObjectParameter("cde_PorcentajeColaborador", typeof(decimal));
    
            var cde_PorcentajeEmpresaParameter = cde_PorcentajeEmpresa.HasValue ?
                new ObjectParameter("cde_PorcentajeEmpresa", cde_PorcentajeEmpresa) :
                new ObjectParameter("cde_PorcentajeEmpresa", typeof(decimal));
    
            var cde_UsuarioModificaParameter = cde_UsuarioModifica.HasValue ?
                new ObjectParameter("cde_UsuarioModifica", cde_UsuarioModifica) :
                new ObjectParameter("cde_UsuarioModifica", typeof(int));
    
            var cde_FechaModificaParameter = cde_FechaModifica.HasValue ?
                new ObjectParameter("cde_FechaModifica", cde_FechaModifica) :
                new ObjectParameter("cde_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbCatalogoDeDeducciones_Update", cde_IdDeduccionParameter, cde_DescripcionDeduParameter, tde_IdTipoDeduParameter, cde_PorcentajeColaboradorParameter, cde_PorcentajeEmpresaParameter, cde_UsuarioModificaParameter, cde_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbCatalogoDeIngresos_Activar(Nullable<int> cin_IdIngreso, Nullable<int> cin_UsuarioModifica, Nullable<System.DateTime> cin_FechaModifica)
        {
            var cin_IdIngresoParameter = cin_IdIngreso.HasValue ?
                new ObjectParameter("cin_IdIngreso", cin_IdIngreso) :
                new ObjectParameter("cin_IdIngreso", typeof(int));
    
            var cin_UsuarioModificaParameter = cin_UsuarioModifica.HasValue ?
                new ObjectParameter("cin_UsuarioModifica", cin_UsuarioModifica) :
                new ObjectParameter("cin_UsuarioModifica", typeof(int));
    
            var cin_FechaModificaParameter = cin_FechaModifica.HasValue ?
                new ObjectParameter("cin_FechaModifica", cin_FechaModifica) :
                new ObjectParameter("cin_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbCatalogoDeIngresos_Activar", cin_IdIngresoParameter, cin_UsuarioModificaParameter, cin_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbCatalogoDeIngresos_Inactivar(Nullable<int> cin_IdIngreso, Nullable<int> cin_UsuarioModifica, Nullable<System.DateTime> cin_FechaModifica)
        {
            var cin_IdIngresoParameter = cin_IdIngreso.HasValue ?
                new ObjectParameter("cin_IdIngreso", cin_IdIngreso) :
                new ObjectParameter("cin_IdIngreso", typeof(int));
    
            var cin_UsuarioModificaParameter = cin_UsuarioModifica.HasValue ?
                new ObjectParameter("cin_UsuarioModifica", cin_UsuarioModifica) :
                new ObjectParameter("cin_UsuarioModifica", typeof(int));
    
            var cin_FechaModificaParameter = cin_FechaModifica.HasValue ?
                new ObjectParameter("cin_FechaModifica", cin_FechaModifica) :
                new ObjectParameter("cin_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbCatalogoDeIngresos_Inactivar", cin_IdIngresoParameter, cin_UsuarioModificaParameter, cin_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbCatalogoDeIngresos_Insert(string cin_DescripcionIngreso, Nullable<int> cin_UsuarioCrea, Nullable<System.DateTime> cin_FechaCrea)
        {
            var cin_DescripcionIngresoParameter = cin_DescripcionIngreso != null ?
                new ObjectParameter("cin_DescripcionIngreso", cin_DescripcionIngreso) :
                new ObjectParameter("cin_DescripcionIngreso", typeof(string));
    
            var cin_UsuarioCreaParameter = cin_UsuarioCrea.HasValue ?
                new ObjectParameter("cin_UsuarioCrea", cin_UsuarioCrea) :
                new ObjectParameter("cin_UsuarioCrea", typeof(int));
    
            var cin_FechaCreaParameter = cin_FechaCrea.HasValue ?
                new ObjectParameter("cin_FechaCrea", cin_FechaCrea) :
                new ObjectParameter("cin_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbCatalogoDeIngresos_Insert", cin_DescripcionIngresoParameter, cin_UsuarioCreaParameter, cin_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbCatalogoDeIngresos_Update(Nullable<int> cin_IdIngreso, string cin_DescripcionIngreso, Nullable<int> cin_UsuarioModifica, Nullable<System.DateTime> cin_FechaModifica)
        {
            var cin_IdIngresoParameter = cin_IdIngreso.HasValue ?
                new ObjectParameter("cin_IdIngreso", cin_IdIngreso) :
                new ObjectParameter("cin_IdIngreso", typeof(int));
    
            var cin_DescripcionIngresoParameter = cin_DescripcionIngreso != null ?
                new ObjectParameter("cin_DescripcionIngreso", cin_DescripcionIngreso) :
                new ObjectParameter("cin_DescripcionIngreso", typeof(string));
    
            var cin_UsuarioModificaParameter = cin_UsuarioModifica.HasValue ?
                new ObjectParameter("cin_UsuarioModifica", cin_UsuarioModifica) :
                new ObjectParameter("cin_UsuarioModifica", typeof(int));
    
            var cin_FechaModificaParameter = cin_FechaModifica.HasValue ?
                new ObjectParameter("cin_FechaModifica", cin_FechaModifica) :
                new ObjectParameter("cin_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbCatalogoDeIngresos_Update", cin_IdIngresoParameter, cin_DescripcionIngresoParameter, cin_UsuarioModificaParameter, cin_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbCatalogoDePlanillas_Inactivar(Nullable<int> cpla_IdPlanilla)
        {
            var cpla_IdPlanillaParameter = cpla_IdPlanilla.HasValue ?
                new ObjectParameter("cpla_IdPlanilla", cpla_IdPlanilla) :
                new ObjectParameter("cpla_IdPlanilla", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbCatalogoDePlanillas_Inactivar", cpla_IdPlanillaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbCatalogoDePlanillas_Insert(string cpla_DescripcionPlanilla, Nullable<int> cpla_FrecuenciaEnDias, Nullable<int> cpla_UsuarioCrea, Nullable<System.DateTime> cpla_FechaCrea, Nullable<bool> cpla_RecibeComision)
        {
            var cpla_DescripcionPlanillaParameter = cpla_DescripcionPlanilla != null ?
                new ObjectParameter("cpla_DescripcionPlanilla", cpla_DescripcionPlanilla) :
                new ObjectParameter("cpla_DescripcionPlanilla", typeof(string));
    
            var cpla_FrecuenciaEnDiasParameter = cpla_FrecuenciaEnDias.HasValue ?
                new ObjectParameter("cpla_FrecuenciaEnDias", cpla_FrecuenciaEnDias) :
                new ObjectParameter("cpla_FrecuenciaEnDias", typeof(int));
    
            var cpla_UsuarioCreaParameter = cpla_UsuarioCrea.HasValue ?
                new ObjectParameter("cpla_UsuarioCrea", cpla_UsuarioCrea) :
                new ObjectParameter("cpla_UsuarioCrea", typeof(int));
    
            var cpla_FechaCreaParameter = cpla_FechaCrea.HasValue ?
                new ObjectParameter("cpla_FechaCrea", cpla_FechaCrea) :
                new ObjectParameter("cpla_FechaCrea", typeof(System.DateTime));
    
            var cpla_RecibeComisionParameter = cpla_RecibeComision.HasValue ?
                new ObjectParameter("cpla_RecibeComision", cpla_RecibeComision) :
                new ObjectParameter("cpla_RecibeComision", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbCatalogoDePlanillas_Insert", cpla_DescripcionPlanillaParameter, cpla_FrecuenciaEnDiasParameter, cpla_UsuarioCreaParameter, cpla_FechaCreaParameter, cpla_RecibeComisionParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbCatalogoDePlanillas_Update(Nullable<int> cpla_IdPlanilla, string cpla_DescripcionPlanilla, Nullable<int> cpla_FrecuenciaEnDias, Nullable<int> cpla_UsuarioModifica, Nullable<System.DateTime> cpla_FechaModifica, Nullable<bool> cpla_RecibeComision)
        {
            var cpla_IdPlanillaParameter = cpla_IdPlanilla.HasValue ?
                new ObjectParameter("cpla_IdPlanilla", cpla_IdPlanilla) :
                new ObjectParameter("cpla_IdPlanilla", typeof(int));
    
            var cpla_DescripcionPlanillaParameter = cpla_DescripcionPlanilla != null ?
                new ObjectParameter("cpla_DescripcionPlanilla", cpla_DescripcionPlanilla) :
                new ObjectParameter("cpla_DescripcionPlanilla", typeof(string));
    
            var cpla_FrecuenciaEnDiasParameter = cpla_FrecuenciaEnDias.HasValue ?
                new ObjectParameter("cpla_FrecuenciaEnDias", cpla_FrecuenciaEnDias) :
                new ObjectParameter("cpla_FrecuenciaEnDias", typeof(int));
    
            var cpla_UsuarioModificaParameter = cpla_UsuarioModifica.HasValue ?
                new ObjectParameter("cpla_UsuarioModifica", cpla_UsuarioModifica) :
                new ObjectParameter("cpla_UsuarioModifica", typeof(int));
    
            var cpla_FechaModificaParameter = cpla_FechaModifica.HasValue ?
                new ObjectParameter("cpla_FechaModifica", cpla_FechaModifica) :
                new ObjectParameter("cpla_FechaModifica", typeof(System.DateTime));
    
            var cpla_RecibeComisionParameter = cpla_RecibeComision.HasValue ?
                new ObjectParameter("cpla_RecibeComision", cpla_RecibeComision) :
                new ObjectParameter("cpla_RecibeComision", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbCatalogoDePlanillas_Update", cpla_IdPlanillaParameter, cpla_DescripcionPlanillaParameter, cpla_FrecuenciaEnDiasParameter, cpla_UsuarioModificaParameter, cpla_FechaModificaParameter, cpla_RecibeComisionParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbDecimoCuartoMes_Insert(Nullable<int> emp_Id, Nullable<decimal> dtm_DecimoCuartoMonto)
        {
            var emp_IdParameter = emp_Id.HasValue ?
                new ObjectParameter("emp_Id", emp_Id) :
                new ObjectParameter("emp_Id", typeof(int));
    
            var dtm_DecimoCuartoMontoParameter = dtm_DecimoCuartoMonto.HasValue ?
                new ObjectParameter("dtm_DecimoCuartoMonto", dtm_DecimoCuartoMonto) :
                new ObjectParameter("dtm_DecimoCuartoMonto", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbDecimoCuartoMes_Insert", emp_IdParameter, dtm_DecimoCuartoMontoParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbDecimoTercerMes_Insert(Nullable<int> emp_Id, Nullable<decimal> dtm_DecimoTercer)
        {
            var emp_IdParameter = emp_Id.HasValue ?
                new ObjectParameter("emp_Id", emp_Id) :
                new ObjectParameter("emp_Id", typeof(int));
    
            var dtm_DecimoTercerParameter = dtm_DecimoTercer.HasValue ?
                new ObjectParameter("dtm_DecimoTercer", dtm_DecimoTercer) :
                new ObjectParameter("dtm_DecimoTercer", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbDecimoTercerMes_Insert", emp_IdParameter, dtm_DecimoTercerParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbDeduccionesExtraordinarias_Activar(Nullable<int> dex_IdDeduccionesExtra, Nullable<int> dex_UsuarioModifica, Nullable<System.DateTime> dex_FechaModifica)
        {
            var dex_IdDeduccionesExtraParameter = dex_IdDeduccionesExtra.HasValue ?
                new ObjectParameter("dex_IdDeduccionesExtra", dex_IdDeduccionesExtra) :
                new ObjectParameter("dex_IdDeduccionesExtra", typeof(int));
    
            var dex_UsuarioModificaParameter = dex_UsuarioModifica.HasValue ?
                new ObjectParameter("dex_UsuarioModifica", dex_UsuarioModifica) :
                new ObjectParameter("dex_UsuarioModifica", typeof(int));
    
            var dex_FechaModificaParameter = dex_FechaModifica.HasValue ?
                new ObjectParameter("dex_FechaModifica", dex_FechaModifica) :
                new ObjectParameter("dex_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbDeduccionesExtraordinarias_Activar", dex_IdDeduccionesExtraParameter, dex_UsuarioModificaParameter, dex_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbDeduccionesExtraordinarias_Inactivar(Nullable<int> dex_IdDeduccionesExtra, Nullable<int> dex_UsuarioModifica, Nullable<System.DateTime> dex_FechaModifica)
        {
            var dex_IdDeduccionesExtraParameter = dex_IdDeduccionesExtra.HasValue ?
                new ObjectParameter("dex_IdDeduccionesExtra", dex_IdDeduccionesExtra) :
                new ObjectParameter("dex_IdDeduccionesExtra", typeof(int));
    
            var dex_UsuarioModificaParameter = dex_UsuarioModifica.HasValue ?
                new ObjectParameter("dex_UsuarioModifica", dex_UsuarioModifica) :
                new ObjectParameter("dex_UsuarioModifica", typeof(int));
    
            var dex_FechaModificaParameter = dex_FechaModifica.HasValue ?
                new ObjectParameter("dex_FechaModifica", dex_FechaModifica) :
                new ObjectParameter("dex_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbDeduccionesExtraordinarias_Inactivar", dex_IdDeduccionesExtraParameter, dex_UsuarioModificaParameter, dex_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbDeduccionesExtraordinarias_Insert(Nullable<int> eqem_Id, Nullable<decimal> dex_MontoInicial, Nullable<decimal> dex_MontoRestante, string dex_ObservacionesComentarios, Nullable<int> cde_IdDeducciones, Nullable<decimal> dex_Cuota, Nullable<int> dex_UsuarioCrea, Nullable<System.DateTime> dex_FechaCrea)
        {
            var eqem_IdParameter = eqem_Id.HasValue ?
                new ObjectParameter("eqem_Id", eqem_Id) :
                new ObjectParameter("eqem_Id", typeof(int));
    
            var dex_MontoInicialParameter = dex_MontoInicial.HasValue ?
                new ObjectParameter("dex_MontoInicial", dex_MontoInicial) :
                new ObjectParameter("dex_MontoInicial", typeof(decimal));
    
            var dex_MontoRestanteParameter = dex_MontoRestante.HasValue ?
                new ObjectParameter("dex_MontoRestante", dex_MontoRestante) :
                new ObjectParameter("dex_MontoRestante", typeof(decimal));
    
            var dex_ObservacionesComentariosParameter = dex_ObservacionesComentarios != null ?
                new ObjectParameter("dex_ObservacionesComentarios", dex_ObservacionesComentarios) :
                new ObjectParameter("dex_ObservacionesComentarios", typeof(string));
    
            var cde_IdDeduccionesParameter = cde_IdDeducciones.HasValue ?
                new ObjectParameter("cde_IdDeducciones", cde_IdDeducciones) :
                new ObjectParameter("cde_IdDeducciones", typeof(int));
    
            var dex_CuotaParameter = dex_Cuota.HasValue ?
                new ObjectParameter("dex_Cuota", dex_Cuota) :
                new ObjectParameter("dex_Cuota", typeof(decimal));
    
            var dex_UsuarioCreaParameter = dex_UsuarioCrea.HasValue ?
                new ObjectParameter("dex_UsuarioCrea", dex_UsuarioCrea) :
                new ObjectParameter("dex_UsuarioCrea", typeof(int));
    
            var dex_FechaCreaParameter = dex_FechaCrea.HasValue ?
                new ObjectParameter("dex_FechaCrea", dex_FechaCrea) :
                new ObjectParameter("dex_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbDeduccionesExtraordinarias_Insert", eqem_IdParameter, dex_MontoInicialParameter, dex_MontoRestanteParameter, dex_ObservacionesComentariosParameter, cde_IdDeduccionesParameter, dex_CuotaParameter, dex_UsuarioCreaParameter, dex_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbDeduccionesExtraordinarias_Update(Nullable<int> dex_IdDeduccionesExtra, Nullable<int> eqem_Id, Nullable<decimal> dex_MontoInicial, Nullable<decimal> dex_MontoRestante, string dex_ObservacionesComentarios, Nullable<int> cde_IdDeducciones, Nullable<decimal> dex_Cuota, Nullable<int> dex_UsuarioModifica, Nullable<System.DateTime> dex_FechaModifica)
        {
            var dex_IdDeduccionesExtraParameter = dex_IdDeduccionesExtra.HasValue ?
                new ObjectParameter("dex_IdDeduccionesExtra", dex_IdDeduccionesExtra) :
                new ObjectParameter("dex_IdDeduccionesExtra", typeof(int));
    
            var eqem_IdParameter = eqem_Id.HasValue ?
                new ObjectParameter("eqem_Id", eqem_Id) :
                new ObjectParameter("eqem_Id", typeof(int));
    
            var dex_MontoInicialParameter = dex_MontoInicial.HasValue ?
                new ObjectParameter("dex_MontoInicial", dex_MontoInicial) :
                new ObjectParameter("dex_MontoInicial", typeof(decimal));
    
            var dex_MontoRestanteParameter = dex_MontoRestante.HasValue ?
                new ObjectParameter("dex_MontoRestante", dex_MontoRestante) :
                new ObjectParameter("dex_MontoRestante", typeof(decimal));
    
            var dex_ObservacionesComentariosParameter = dex_ObservacionesComentarios != null ?
                new ObjectParameter("dex_ObservacionesComentarios", dex_ObservacionesComentarios) :
                new ObjectParameter("dex_ObservacionesComentarios", typeof(string));
    
            var cde_IdDeduccionesParameter = cde_IdDeducciones.HasValue ?
                new ObjectParameter("cde_IdDeducciones", cde_IdDeducciones) :
                new ObjectParameter("cde_IdDeducciones", typeof(int));
    
            var dex_CuotaParameter = dex_Cuota.HasValue ?
                new ObjectParameter("dex_Cuota", dex_Cuota) :
                new ObjectParameter("dex_Cuota", typeof(decimal));
    
            var dex_UsuarioModificaParameter = dex_UsuarioModifica.HasValue ?
                new ObjectParameter("dex_UsuarioModifica", dex_UsuarioModifica) :
                new ObjectParameter("dex_UsuarioModifica", typeof(int));
    
            var dex_FechaModificaParameter = dex_FechaModifica.HasValue ?
                new ObjectParameter("dex_FechaModifica", dex_FechaModifica) :
                new ObjectParameter("dex_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbDeduccionesExtraordinarias_Update", dex_IdDeduccionesExtraParameter, eqem_IdParameter, dex_MontoInicialParameter, dex_MontoRestanteParameter, dex_ObservacionesComentariosParameter, cde_IdDeduccionesParameter, dex_CuotaParameter, dex_UsuarioModificaParameter, dex_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbEmpleadoBonos_Activar(Nullable<int> cb_Id, Nullable<int> cb_UsuarioModifica, Nullable<System.DateTime> cb_FechaModifica)
        {
            var cb_IdParameter = cb_Id.HasValue ?
                new ObjectParameter("cb_Id", cb_Id) :
                new ObjectParameter("cb_Id", typeof(int));
    
            var cb_UsuarioModificaParameter = cb_UsuarioModifica.HasValue ?
                new ObjectParameter("cb_UsuarioModifica", cb_UsuarioModifica) :
                new ObjectParameter("cb_UsuarioModifica", typeof(int));
    
            var cb_FechaModificaParameter = cb_FechaModifica.HasValue ?
                new ObjectParameter("cb_FechaModifica", cb_FechaModifica) :
                new ObjectParameter("cb_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbEmpleadoBonos_Activar", cb_IdParameter, cb_UsuarioModificaParameter, cb_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbEmpleadoBonos_Inactivar(Nullable<int> cb_Id, Nullable<int> cb_UsuarioModifica, Nullable<System.DateTime> cb_FechaModifica)
        {
            var cb_IdParameter = cb_Id.HasValue ?
                new ObjectParameter("cb_Id", cb_Id) :
                new ObjectParameter("cb_Id", typeof(int));
    
            var cb_UsuarioModificaParameter = cb_UsuarioModifica.HasValue ?
                new ObjectParameter("cb_UsuarioModifica", cb_UsuarioModifica) :
                new ObjectParameter("cb_UsuarioModifica", typeof(int));
    
            var cb_FechaModificaParameter = cb_FechaModifica.HasValue ?
                new ObjectParameter("cb_FechaModifica", cb_FechaModifica) :
                new ObjectParameter("cb_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbEmpleadoBonos_Inactivar", cb_IdParameter, cb_UsuarioModificaParameter, cb_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbEmpleadoBonos_Insert(Nullable<int> emp_Id, Nullable<int> cin_IdIngreso, Nullable<decimal> cb_Monto, Nullable<System.DateTime> cb_FechaRegistro, Nullable<bool> cb_Pagado, Nullable<int> cb_UsuarioCrea, Nullable<System.DateTime> cb_FechaCrea)
        {
            var emp_IdParameter = emp_Id.HasValue ?
                new ObjectParameter("emp_Id", emp_Id) :
                new ObjectParameter("emp_Id", typeof(int));
    
            var cin_IdIngresoParameter = cin_IdIngreso.HasValue ?
                new ObjectParameter("cin_IdIngreso", cin_IdIngreso) :
                new ObjectParameter("cin_IdIngreso", typeof(int));
    
            var cb_MontoParameter = cb_Monto.HasValue ?
                new ObjectParameter("cb_Monto", cb_Monto) :
                new ObjectParameter("cb_Monto", typeof(decimal));
    
            var cb_FechaRegistroParameter = cb_FechaRegistro.HasValue ?
                new ObjectParameter("cb_FechaRegistro", cb_FechaRegistro) :
                new ObjectParameter("cb_FechaRegistro", typeof(System.DateTime));
    
            var cb_PagadoParameter = cb_Pagado.HasValue ?
                new ObjectParameter("cb_Pagado", cb_Pagado) :
                new ObjectParameter("cb_Pagado", typeof(bool));
    
            var cb_UsuarioCreaParameter = cb_UsuarioCrea.HasValue ?
                new ObjectParameter("cb_UsuarioCrea", cb_UsuarioCrea) :
                new ObjectParameter("cb_UsuarioCrea", typeof(int));
    
            var cb_FechaCreaParameter = cb_FechaCrea.HasValue ?
                new ObjectParameter("cb_FechaCrea", cb_FechaCrea) :
                new ObjectParameter("cb_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbEmpleadoBonos_Insert", emp_IdParameter, cin_IdIngresoParameter, cb_MontoParameter, cb_FechaRegistroParameter, cb_PagadoParameter, cb_UsuarioCreaParameter, cb_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbEmpleadoBonos_Update(Nullable<int> cb_Id, Nullable<int> emp_Id, Nullable<int> cin_IdIngreso, Nullable<decimal> cb_Monto, Nullable<System.DateTime> cb_FechaRegistro, Nullable<bool> cb_Pagado, Nullable<int> cb_UsuarioModifica, Nullable<System.DateTime> cb_FechaModifica)
        {
            var cb_IdParameter = cb_Id.HasValue ?
                new ObjectParameter("cb_Id", cb_Id) :
                new ObjectParameter("cb_Id", typeof(int));
    
            var emp_IdParameter = emp_Id.HasValue ?
                new ObjectParameter("emp_Id", emp_Id) :
                new ObjectParameter("emp_Id", typeof(int));
    
            var cin_IdIngresoParameter = cin_IdIngreso.HasValue ?
                new ObjectParameter("cin_IdIngreso", cin_IdIngreso) :
                new ObjectParameter("cin_IdIngreso", typeof(int));
    
            var cb_MontoParameter = cb_Monto.HasValue ?
                new ObjectParameter("cb_Monto", cb_Monto) :
                new ObjectParameter("cb_Monto", typeof(decimal));
    
            var cb_FechaRegistroParameter = cb_FechaRegistro.HasValue ?
                new ObjectParameter("cb_FechaRegistro", cb_FechaRegistro) :
                new ObjectParameter("cb_FechaRegistro", typeof(System.DateTime));
    
            var cb_PagadoParameter = cb_Pagado.HasValue ?
                new ObjectParameter("cb_Pagado", cb_Pagado) :
                new ObjectParameter("cb_Pagado", typeof(bool));
    
            var cb_UsuarioModificaParameter = cb_UsuarioModifica.HasValue ?
                new ObjectParameter("cb_UsuarioModifica", cb_UsuarioModifica) :
                new ObjectParameter("cb_UsuarioModifica", typeof(int));
    
            var cb_FechaModificaParameter = cb_FechaModifica.HasValue ?
                new ObjectParameter("cb_FechaModifica", cb_FechaModifica) :
                new ObjectParameter("cb_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbEmpleadoBonos_Update", cb_IdParameter, emp_IdParameter, cin_IdIngresoParameter, cb_MontoParameter, cb_FechaRegistroParameter, cb_PagadoParameter, cb_UsuarioModificaParameter, cb_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbFormaPago_Activar(Nullable<int> fpa_IdFormaPago, Nullable<int> fpa_UsuarioModifica, Nullable<System.DateTime> fpa_FechaModifica)
        {
            var fpa_IdFormaPagoParameter = fpa_IdFormaPago.HasValue ?
                new ObjectParameter("fpa_IdFormaPago", fpa_IdFormaPago) :
                new ObjectParameter("fpa_IdFormaPago", typeof(int));
    
            var fpa_UsuarioModificaParameter = fpa_UsuarioModifica.HasValue ?
                new ObjectParameter("fpa_UsuarioModifica", fpa_UsuarioModifica) :
                new ObjectParameter("fpa_UsuarioModifica", typeof(int));
    
            var fpa_FechaModificaParameter = fpa_FechaModifica.HasValue ?
                new ObjectParameter("fpa_FechaModifica", fpa_FechaModifica) :
                new ObjectParameter("fpa_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbFormaPago_Activar", fpa_IdFormaPagoParameter, fpa_UsuarioModificaParameter, fpa_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbFormaPago_Inactivar(Nullable<int> fpa_IdFormaPago, Nullable<int> fpa_UsuarioModifica, Nullable<System.DateTime> fpa_FechaModifica)
        {
            var fpa_IdFormaPagoParameter = fpa_IdFormaPago.HasValue ?
                new ObjectParameter("fpa_IdFormaPago", fpa_IdFormaPago) :
                new ObjectParameter("fpa_IdFormaPago", typeof(int));
    
            var fpa_UsuarioModificaParameter = fpa_UsuarioModifica.HasValue ?
                new ObjectParameter("fpa_UsuarioModifica", fpa_UsuarioModifica) :
                new ObjectParameter("fpa_UsuarioModifica", typeof(int));
    
            var fpa_FechaModificaParameter = fpa_FechaModifica.HasValue ?
                new ObjectParameter("fpa_FechaModifica", fpa_FechaModifica) :
                new ObjectParameter("fpa_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbFormaPago_Inactivar", fpa_IdFormaPagoParameter, fpa_UsuarioModificaParameter, fpa_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbFormaPago_Insert(string fpa_Descripcion, Nullable<int> fpa_UsuarioCrea, Nullable<System.DateTime> fpa_FechaCrea)
        {
            var fpa_DescripcionParameter = fpa_Descripcion != null ?
                new ObjectParameter("fpa_Descripcion", fpa_Descripcion) :
                new ObjectParameter("fpa_Descripcion", typeof(string));
    
            var fpa_UsuarioCreaParameter = fpa_UsuarioCrea.HasValue ?
                new ObjectParameter("fpa_UsuarioCrea", fpa_UsuarioCrea) :
                new ObjectParameter("fpa_UsuarioCrea", typeof(int));
    
            var fpa_FechaCreaParameter = fpa_FechaCrea.HasValue ?
                new ObjectParameter("fpa_FechaCrea", fpa_FechaCrea) :
                new ObjectParameter("fpa_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbFormaPago_Insert", fpa_DescripcionParameter, fpa_UsuarioCreaParameter, fpa_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbFormaPago_Update(Nullable<int> fpa_IdFormaPago, string fpa_Descripcion, Nullable<int> fpa_UsuarioModifica, Nullable<System.DateTime> fpa_FechaModifica)
        {
            var fpa_IdFormaPagoParameter = fpa_IdFormaPago.HasValue ?
                new ObjectParameter("fpa_IdFormaPago", fpa_IdFormaPago) :
                new ObjectParameter("fpa_IdFormaPago", typeof(int));
    
            var fpa_DescripcionParameter = fpa_Descripcion != null ?
                new ObjectParameter("fpa_Descripcion", fpa_Descripcion) :
                new ObjectParameter("fpa_Descripcion", typeof(string));
    
            var fpa_UsuarioModificaParameter = fpa_UsuarioModifica.HasValue ?
                new ObjectParameter("fpa_UsuarioModifica", fpa_UsuarioModifica) :
                new ObjectParameter("fpa_UsuarioModifica", typeof(int));
    
            var fpa_FechaModificaParameter = fpa_FechaModifica.HasValue ?
                new ObjectParameter("fpa_FechaModifica", fpa_FechaModifica) :
                new ObjectParameter("fpa_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbFormaPago_Update", fpa_IdFormaPagoParameter, fpa_DescripcionParameter, fpa_UsuarioModificaParameter, fpa_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbInstitucionesFinancieras_Insert(string insf_DescInstitucionFinanc, string insf_Contacto, string insf_Telefono, string insf_Correo, Nullable<int> insf_UsuarioCrea, Nullable<System.DateTime> insf_FechaCrea, Nullable<bool> insf_Activo)
        {
            var insf_DescInstitucionFinancParameter = insf_DescInstitucionFinanc != null ?
                new ObjectParameter("insf_DescInstitucionFinanc", insf_DescInstitucionFinanc) :
                new ObjectParameter("insf_DescInstitucionFinanc", typeof(string));
    
            var insf_ContactoParameter = insf_Contacto != null ?
                new ObjectParameter("insf_Contacto", insf_Contacto) :
                new ObjectParameter("insf_Contacto", typeof(string));
    
            var insf_TelefonoParameter = insf_Telefono != null ?
                new ObjectParameter("insf_Telefono", insf_Telefono) :
                new ObjectParameter("insf_Telefono", typeof(string));
    
            var insf_CorreoParameter = insf_Correo != null ?
                new ObjectParameter("insf_Correo", insf_Correo) :
                new ObjectParameter("insf_Correo", typeof(string));
    
            var insf_UsuarioCreaParameter = insf_UsuarioCrea.HasValue ?
                new ObjectParameter("insf_UsuarioCrea", insf_UsuarioCrea) :
                new ObjectParameter("insf_UsuarioCrea", typeof(int));
    
            var insf_FechaCreaParameter = insf_FechaCrea.HasValue ?
                new ObjectParameter("insf_FechaCrea", insf_FechaCrea) :
                new ObjectParameter("insf_FechaCrea", typeof(System.DateTime));
    
            var insf_ActivoParameter = insf_Activo.HasValue ?
                new ObjectParameter("insf_Activo", insf_Activo) :
                new ObjectParameter("insf_Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbInstitucionesFinancieras_Insert", insf_DescInstitucionFinancParameter, insf_ContactoParameter, insf_TelefonoParameter, insf_CorreoParameter, insf_UsuarioCreaParameter, insf_FechaCreaParameter, insf_ActivoParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbInstitucionesFinancieras_Update(Nullable<int> insf_IdInstitucionFinanciera, string insf_DescInstitucionFinanc, string insf_Contacto, string insf_Telefono, string insf_Correo, Nullable<int> insf_UsuarioModifica, Nullable<System.DateTime> insf_FechaModifica, Nullable<bool> insf_Activo)
        {
            var insf_IdInstitucionFinancieraParameter = insf_IdInstitucionFinanciera.HasValue ?
                new ObjectParameter("insf_IdInstitucionFinanciera", insf_IdInstitucionFinanciera) :
                new ObjectParameter("insf_IdInstitucionFinanciera", typeof(int));
    
            var insf_DescInstitucionFinancParameter = insf_DescInstitucionFinanc != null ?
                new ObjectParameter("insf_DescInstitucionFinanc", insf_DescInstitucionFinanc) :
                new ObjectParameter("insf_DescInstitucionFinanc", typeof(string));
    
            var insf_ContactoParameter = insf_Contacto != null ?
                new ObjectParameter("insf_Contacto", insf_Contacto) :
                new ObjectParameter("insf_Contacto", typeof(string));
    
            var insf_TelefonoParameter = insf_Telefono != null ?
                new ObjectParameter("insf_Telefono", insf_Telefono) :
                new ObjectParameter("insf_Telefono", typeof(string));
    
            var insf_CorreoParameter = insf_Correo != null ?
                new ObjectParameter("insf_Correo", insf_Correo) :
                new ObjectParameter("insf_Correo", typeof(string));
    
            var insf_UsuarioModificaParameter = insf_UsuarioModifica.HasValue ?
                new ObjectParameter("insf_UsuarioModifica", insf_UsuarioModifica) :
                new ObjectParameter("insf_UsuarioModifica", typeof(int));
    
            var insf_FechaModificaParameter = insf_FechaModifica.HasValue ?
                new ObjectParameter("insf_FechaModifica", insf_FechaModifica) :
                new ObjectParameter("insf_FechaModifica", typeof(System.DateTime));
    
            var insf_ActivoParameter = insf_Activo.HasValue ?
                new ObjectParameter("insf_Activo", insf_Activo) :
                new ObjectParameter("insf_Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbInstitucionesFinancieras_Update", insf_IdInstitucionFinancieraParameter, insf_DescInstitucionFinancParameter, insf_ContactoParameter, insf_TelefonoParameter, insf_CorreoParameter, insf_UsuarioModificaParameter, insf_FechaModificaParameter, insf_ActivoParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbISR_Activar(Nullable<int> isr_Id, Nullable<int> isr_UsuarioModifica, Nullable<System.DateTime> isr_FechaModifica)
        {
            var isr_IdParameter = isr_Id.HasValue ?
                new ObjectParameter("isr_Id", isr_Id) :
                new ObjectParameter("isr_Id", typeof(int));
    
            var isr_UsuarioModificaParameter = isr_UsuarioModifica.HasValue ?
                new ObjectParameter("isr_UsuarioModifica", isr_UsuarioModifica) :
                new ObjectParameter("isr_UsuarioModifica", typeof(int));
    
            var isr_FechaModificaParameter = isr_FechaModifica.HasValue ?
                new ObjectParameter("isr_FechaModifica", isr_FechaModifica) :
                new ObjectParameter("isr_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbISR_Activar", isr_IdParameter, isr_UsuarioModificaParameter, isr_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbISR_Inactivar(Nullable<int> isr_Id, Nullable<int> isr_UsuarioModifica, Nullable<System.DateTime> isr_FechaModifica)
        {
            var isr_IdParameter = isr_Id.HasValue ?
                new ObjectParameter("isr_Id", isr_Id) :
                new ObjectParameter("isr_Id", typeof(int));
    
            var isr_UsuarioModificaParameter = isr_UsuarioModifica.HasValue ?
                new ObjectParameter("isr_UsuarioModifica", isr_UsuarioModifica) :
                new ObjectParameter("isr_UsuarioModifica", typeof(int));
    
            var isr_FechaModificaParameter = isr_FechaModifica.HasValue ?
                new ObjectParameter("isr_FechaModifica", isr_FechaModifica) :
                new ObjectParameter("isr_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbISR_Inactivar", isr_IdParameter, isr_UsuarioModificaParameter, isr_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbISR_Insert(Nullable<decimal> isr_RangoInicial, Nullable<decimal> isr_RangoFinal, Nullable<decimal> isr_Porcentaje, Nullable<int> tde_IdTipoDedu, Nullable<int> isr_UsuarioCrea, Nullable<System.DateTime> isr_FechaCrea)
        {
            var isr_RangoInicialParameter = isr_RangoInicial.HasValue ?
                new ObjectParameter("isr_RangoInicial", isr_RangoInicial) :
                new ObjectParameter("isr_RangoInicial", typeof(decimal));
    
            var isr_RangoFinalParameter = isr_RangoFinal.HasValue ?
                new ObjectParameter("isr_RangoFinal", isr_RangoFinal) :
                new ObjectParameter("isr_RangoFinal", typeof(decimal));
    
            var isr_PorcentajeParameter = isr_Porcentaje.HasValue ?
                new ObjectParameter("isr_Porcentaje", isr_Porcentaje) :
                new ObjectParameter("isr_Porcentaje", typeof(decimal));
    
            var tde_IdTipoDeduParameter = tde_IdTipoDedu.HasValue ?
                new ObjectParameter("tde_IdTipoDedu", tde_IdTipoDedu) :
                new ObjectParameter("tde_IdTipoDedu", typeof(int));
    
            var isr_UsuarioCreaParameter = isr_UsuarioCrea.HasValue ?
                new ObjectParameter("isr_UsuarioCrea", isr_UsuarioCrea) :
                new ObjectParameter("isr_UsuarioCrea", typeof(int));
    
            var isr_FechaCreaParameter = isr_FechaCrea.HasValue ?
                new ObjectParameter("isr_FechaCrea", isr_FechaCrea) :
                new ObjectParameter("isr_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbISR_Insert", isr_RangoInicialParameter, isr_RangoFinalParameter, isr_PorcentajeParameter, tde_IdTipoDeduParameter, isr_UsuarioCreaParameter, isr_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbISR_Update(Nullable<int> isr_Id, Nullable<decimal> isr_RangoInicial, Nullable<decimal> isr_RangoFinal, Nullable<decimal> isr_Porcentaje, Nullable<int> tde_IdTipoDedu, Nullable<int> isr_UsuarioModifica, Nullable<System.DateTime> isr_FechaModifica)
        {
            var isr_IdParameter = isr_Id.HasValue ?
                new ObjectParameter("isr_Id", isr_Id) :
                new ObjectParameter("isr_Id", typeof(int));
    
            var isr_RangoInicialParameter = isr_RangoInicial.HasValue ?
                new ObjectParameter("isr_RangoInicial", isr_RangoInicial) :
                new ObjectParameter("isr_RangoInicial", typeof(decimal));
    
            var isr_RangoFinalParameter = isr_RangoFinal.HasValue ?
                new ObjectParameter("isr_RangoFinal", isr_RangoFinal) :
                new ObjectParameter("isr_RangoFinal", typeof(decimal));
    
            var isr_PorcentajeParameter = isr_Porcentaje.HasValue ?
                new ObjectParameter("isr_Porcentaje", isr_Porcentaje) :
                new ObjectParameter("isr_Porcentaje", typeof(decimal));
    
            var tde_IdTipoDeduParameter = tde_IdTipoDedu.HasValue ?
                new ObjectParameter("tde_IdTipoDedu", tde_IdTipoDedu) :
                new ObjectParameter("tde_IdTipoDedu", typeof(int));
    
            var isr_UsuarioModificaParameter = isr_UsuarioModifica.HasValue ?
                new ObjectParameter("isr_UsuarioModifica", isr_UsuarioModifica) :
                new ObjectParameter("isr_UsuarioModifica", typeof(int));
    
            var isr_FechaModificaParameter = isr_FechaModifica.HasValue ?
                new ObjectParameter("isr_FechaModifica", isr_FechaModifica) :
                new ObjectParameter("isr_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbISR_Update", isr_IdParameter, isr_RangoInicialParameter, isr_RangoFinalParameter, isr_PorcentajeParameter, tde_IdTipoDeduParameter, isr_UsuarioModificaParameter, isr_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbTipoDeduccion_Activar(Nullable<int> tde_IdTipoDedu, Nullable<int> tde_UsuarioModifica, Nullable<System.DateTime> tde_FechaModifica)
        {
            var tde_IdTipoDeduParameter = tde_IdTipoDedu.HasValue ?
                new ObjectParameter("tde_IdTipoDedu", tde_IdTipoDedu) :
                new ObjectParameter("tde_IdTipoDedu", typeof(int));
    
            var tde_UsuarioModificaParameter = tde_UsuarioModifica.HasValue ?
                new ObjectParameter("tde_UsuarioModifica", tde_UsuarioModifica) :
                new ObjectParameter("tde_UsuarioModifica", typeof(int));
    
            var tde_FechaModificaParameter = tde_FechaModifica.HasValue ?
                new ObjectParameter("tde_FechaModifica", tde_FechaModifica) :
                new ObjectParameter("tde_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbTipoDeduccion_Activar", tde_IdTipoDeduParameter, tde_UsuarioModificaParameter, tde_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbTipoDeduccion_Inactivar(Nullable<int> tde_IdTipoDedu, Nullable<int> tde_UsuarioModifica, Nullable<System.DateTime> tde_FechaModifica)
        {
            var tde_IdTipoDeduParameter = tde_IdTipoDedu.HasValue ?
                new ObjectParameter("tde_IdTipoDedu", tde_IdTipoDedu) :
                new ObjectParameter("tde_IdTipoDedu", typeof(int));
    
            var tde_UsuarioModificaParameter = tde_UsuarioModifica.HasValue ?
                new ObjectParameter("tde_UsuarioModifica", tde_UsuarioModifica) :
                new ObjectParameter("tde_UsuarioModifica", typeof(int));
    
            var tde_FechaModificaParameter = tde_FechaModifica.HasValue ?
                new ObjectParameter("tde_FechaModifica", tde_FechaModifica) :
                new ObjectParameter("tde_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbTipoDeduccion_Inactivar", tde_IdTipoDeduParameter, tde_UsuarioModificaParameter, tde_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbTipoDeduccion_Insert(string tde_Descripcion, Nullable<int> tde_UsuarioCrea, Nullable<System.DateTime> tde_FechaCrea)
        {
            var tde_DescripcionParameter = tde_Descripcion != null ?
                new ObjectParameter("tde_Descripcion", tde_Descripcion) :
                new ObjectParameter("tde_Descripcion", typeof(string));
    
            var tde_UsuarioCreaParameter = tde_UsuarioCrea.HasValue ?
                new ObjectParameter("tde_UsuarioCrea", tde_UsuarioCrea) :
                new ObjectParameter("tde_UsuarioCrea", typeof(int));
    
            var tde_FechaCreaParameter = tde_FechaCrea.HasValue ?
                new ObjectParameter("tde_FechaCrea", tde_FechaCrea) :
                new ObjectParameter("tde_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbTipoDeduccion_Insert", tde_DescripcionParameter, tde_UsuarioCreaParameter, tde_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_Plani_tbTipoDeduccion_Update(Nullable<int> tde_IdTipoDedu, string tde_Descripcion, Nullable<int> tde_UsuarioModifica, Nullable<System.DateTime> tde_FechaModifica)
        {
            var tde_IdTipoDeduParameter = tde_IdTipoDedu.HasValue ?
                new ObjectParameter("tde_IdTipoDedu", tde_IdTipoDedu) :
                new ObjectParameter("tde_IdTipoDedu", typeof(int));
    
            var tde_DescripcionParameter = tde_Descripcion != null ?
                new ObjectParameter("tde_Descripcion", tde_Descripcion) :
                new ObjectParameter("tde_Descripcion", typeof(string));
    
            var tde_UsuarioModificaParameter = tde_UsuarioModifica.HasValue ?
                new ObjectParameter("tde_UsuarioModifica", tde_UsuarioModifica) :
                new ObjectParameter("tde_UsuarioModifica", typeof(int));
    
            var tde_FechaModificaParameter = tde_FechaModifica.HasValue ?
                new ObjectParameter("tde_FechaModifica", tde_FechaModifica) :
                new ObjectParameter("tde_FechaModifica", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_Plani_tbTipoDeduccion_Update", tde_IdTipoDeduParameter, tde_DescripcionParameter, tde_UsuarioModificaParameter, tde_FechaModificaParameter);
        }
    
        public virtual ObjectResult<string> UDP_tbTipoPlanillaDetalleDeduccion_Insert(Nullable<int> cde_IdDeducciones, Nullable<int> cpla_IdPlanilla, Nullable<int> tpdd_UsuarioCrea, Nullable<System.DateTime> tpdd_FechaCrea)
        {
            var cde_IdDeduccionesParameter = cde_IdDeducciones.HasValue ?
                new ObjectParameter("cde_IdDeducciones", cde_IdDeducciones) :
                new ObjectParameter("cde_IdDeducciones", typeof(int));
    
            var cpla_IdPlanillaParameter = cpla_IdPlanilla.HasValue ?
                new ObjectParameter("cpla_IdPlanilla", cpla_IdPlanilla) :
                new ObjectParameter("cpla_IdPlanilla", typeof(int));
    
            var tpdd_UsuarioCreaParameter = tpdd_UsuarioCrea.HasValue ?
                new ObjectParameter("tpdd_UsuarioCrea", tpdd_UsuarioCrea) :
                new ObjectParameter("tpdd_UsuarioCrea", typeof(int));
    
            var tpdd_FechaCreaParameter = tpdd_FechaCrea.HasValue ?
                new ObjectParameter("tpdd_FechaCrea", tpdd_FechaCrea) :
                new ObjectParameter("tpdd_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_tbTipoPlanillaDetalleDeduccion_Insert", cde_IdDeduccionesParameter, cpla_IdPlanillaParameter, tpdd_UsuarioCreaParameter, tpdd_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_tbTipoPlanillaDetalleDeduccion_Update(Nullable<int> tpdd_IdPlanillaDetDeduccion)
        {
            var tpdd_IdPlanillaDetDeduccionParameter = tpdd_IdPlanillaDetDeduccion.HasValue ?
                new ObjectParameter("tpdd_IdPlanillaDetDeduccion", tpdd_IdPlanillaDetDeduccion) :
                new ObjectParameter("tpdd_IdPlanillaDetDeduccion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_tbTipoPlanillaDetalleDeduccion_Update", tpdd_IdPlanillaDetDeduccionParameter);
        }
    
        public virtual ObjectResult<string> UDP_tbTipoPlanillaDetalleIngreso_Insert(Nullable<int> cin_IdIngreso, Nullable<int> cpla_IdPlanilla, Nullable<int> tpdi_UsuarioCrea, Nullable<System.DateTime> tpdi_FechaCrea)
        {
            var cin_IdIngresoParameter = cin_IdIngreso.HasValue ?
                new ObjectParameter("cin_IdIngreso", cin_IdIngreso) :
                new ObjectParameter("cin_IdIngreso", typeof(int));
    
            var cpla_IdPlanillaParameter = cpla_IdPlanilla.HasValue ?
                new ObjectParameter("cpla_IdPlanilla", cpla_IdPlanilla) :
                new ObjectParameter("cpla_IdPlanilla", typeof(int));
    
            var tpdi_UsuarioCreaParameter = tpdi_UsuarioCrea.HasValue ?
                new ObjectParameter("tpdi_UsuarioCrea", tpdi_UsuarioCrea) :
                new ObjectParameter("tpdi_UsuarioCrea", typeof(int));
    
            var tpdi_FechaCreaParameter = tpdi_FechaCrea.HasValue ?
                new ObjectParameter("tpdi_FechaCrea", tpdi_FechaCrea) :
                new ObjectParameter("tpdi_FechaCrea", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_tbTipoPlanillaDetalleIngreso_Insert", cin_IdIngresoParameter, cpla_IdPlanillaParameter, tpdi_UsuarioCreaParameter, tpdi_FechaCreaParameter);
        }
    
        public virtual ObjectResult<string> UDP_tbTipoPlanillaDetalleIngreso_Update(Nullable<int> tpdi_IdDetallePlanillaIngreso)
        {
            var tpdi_IdDetallePlanillaIngresoParameter = tpdi_IdDetallePlanillaIngreso.HasValue ?
                new ObjectParameter("tpdi_IdDetallePlanillaIngreso", tpdi_IdDetallePlanillaIngreso) :
                new ObjectParameter("tpdi_IdDetallePlanillaIngreso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UDP_tbTipoPlanillaDetalleIngreso_Update", tpdi_IdDetallePlanillaIngresoParameter);
        }
    }
}
