//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DecimoTercerMes_RPT
    {
        public int Codigo_Aguinaldo { get; set; }
        public Nullable<int> Codigo_Empleado { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime Fecha_Pago { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Cuenta_Bancaria { get; set; }
        public string Codigo_Pago { get; set; }
        public string Tipo_Planilla { get; set; }
    }
}
