//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Plani_ReporteIHSS
    {
        public int Id_Empleado { get; set; }
        public Nullable<int> Id_Planilla { get; set; }
        public string Descripcion_Planilla { get; set; }
        public string Nombre_Completo { get; set; }
        public string Identidad { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Correo_Electronico { get; set; }
        public string Estado_Civil { get; set; }
        public Nullable<decimal> Sueldo_Neto { get; set; }
        public Nullable<decimal> Cantidad_IHSS_Empresa { get; set; }
        public Nullable<decimal> Cantidad_IHSS_Colaborador { get; set; }
        public Nullable<decimal> Total_IHSS { get; set; }
        public System.DateTime Fecha_Pago { get; set; }
        public bool Estado_Empleado { get; set; }
    }
}
